//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Antivir.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="Antivir">
 *   <restriction base="{}string">
 *     <enumeration value="off"/>
 *     <enumeration value="inout"/>
 *     <enumeration value="in"/>
 *     <enumeration value="out"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "Antivir")
@XmlEnum
public enum Antivir {

    @XmlEnumValue("off")
    OFF("off"),
    @XmlEnumValue("inout")
    INOUT("inout"),
    @XmlEnumValue("in")
    IN("in"),
    @XmlEnumValue("out")
    OUT("out");
    private final String value;

    Antivir(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Antivir fromValue(String v) {
        for (Antivir c: Antivir.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
