//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for certificateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="certificateType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <choice>
 *           <element name="webspace" type="{}domainName"/>
 *           <element name="site" type="{}domainName"/>
 *           <element name="admin" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         </choice>
 *         <element name="content">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="csr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="pvt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="cert" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   <element name="ca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="ip_address" type="{}ip_address" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "certificateType", propOrder = {
    "name",
    "webspace",
    "site",
    "admin",
    "content",
    "ipAddress"
})
public class CertificateType {

    @XmlElement(required = true)
    protected String name;
    protected String webspace;
    protected String site;
    protected Object admin;
    @XmlElement(required = true)
    protected CertificateType.Content content;
    @XmlElement(name = "ip_address")
    protected String ipAddress;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the webspace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebspace() {
        return webspace;
    }

    /**
     * Sets the value of the webspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebspace(String value) {
        this.webspace = value;
    }

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSite(String value) {
        this.site = value;
    }

    /**
     * Gets the value of the admin property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAdmin() {
        return admin;
    }

    /**
     * Sets the value of the admin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAdmin(Object value) {
        this.admin = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateType.Content }
     *     
     */
    public CertificateType.Content getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateType.Content }
     *     
     */
    public void setContent(CertificateType.Content value) {
        this.content = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="csr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="pvt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="cert" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         <element name="ca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "csr",
        "pvt",
        "cert",
        "ca"
    })
    public static class Content {

        @XmlElement(required = true)
        protected String csr;
        @XmlElement(required = true)
        protected String pvt;
        protected String cert;
        protected String ca;

        /**
         * Gets the value of the csr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCsr() {
            return csr;
        }

        /**
         * Sets the value of the csr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCsr(String value) {
            this.csr = value;
        }

        /**
         * Gets the value of the pvt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPvt() {
            return pvt;
        }

        /**
         * Sets the value of the pvt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPvt(String value) {
            this.pvt = value;
        }

        /**
         * Gets the value of the cert property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCert() {
            return cert;
        }

        /**
         * Sets the value of the cert property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCert(String value) {
            this.cert = value;
        }

        /**
         * Gets the value of the ca property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCa() {
            return ca;
        }

        /**
         * Sets the value of the ca property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCa(String value) {
            this.ca = value;
        }

    }

}
