//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Client statistics
 * 
 * <p>Java class for clientStatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="clientStatType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="active_domains" type="{}unsignedInt"/>
 *         <element name="subdomains" type="{}unsignedInt"/>
 *         <element name="disk_space" type="{}size"/>
 *         <element name="postboxs" type="{}unsignedInt"/>
 *         <element name="redirects" type="{}unsignedInt"/>
 *         <element name="mail_groups" type="{}unsignedInt"/>
 *         <element name="mail_resps" type="{}unsignedInt"/>
 *         <element name="mail_lists" type="{}unsignedInt"/>
 *         <element name="web_users" type="{}unsignedInt"/>
 *         <element name="data_bases" type="{}unsignedInt"/>
 *         <element name="traffic" type="{}size"/>
 *         <element name="traffic_prevday" type="{}size"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clientStatType", propOrder = {
    "activeDomains",
    "subdomains",
    "diskSpace",
    "postboxs",
    "redirects",
    "mailGroups",
    "mailResps",
    "mailLists",
    "webUsers",
    "dataBases",
    "traffic",
    "trafficPrevday"
})
public class ClientStatType {

    @XmlElement(name = "active_domains", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long activeDomains;
    @XmlElement(defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long subdomains;
    @XmlElement(name = "disk_space", required = true, defaultValue = "0")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger diskSpace;
    @XmlElement(defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long postboxs;
    @XmlElement(defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long redirects;
    @XmlElement(name = "mail_groups", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long mailGroups;
    @XmlElement(name = "mail_resps", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long mailResps;
    @XmlElement(name = "mail_lists", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long mailLists;
    @XmlElement(name = "web_users", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long webUsers;
    @XmlElement(name = "data_bases", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long dataBases;
    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger traffic;
    @XmlElement(name = "traffic_prevday", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger trafficPrevday;

    /**
     * Gets the value of the activeDomains property.
     * 
     */
    public long getActiveDomains() {
        return activeDomains;
    }

    /**
     * Sets the value of the activeDomains property.
     * 
     */
    public void setActiveDomains(long value) {
        this.activeDomains = value;
    }

    /**
     * Gets the value of the subdomains property.
     * 
     */
    public long getSubdomains() {
        return subdomains;
    }

    /**
     * Sets the value of the subdomains property.
     * 
     */
    public void setSubdomains(long value) {
        this.subdomains = value;
    }

    /**
     * Gets the value of the diskSpace property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDiskSpace() {
        return diskSpace;
    }

    /**
     * Sets the value of the diskSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDiskSpace(BigInteger value) {
        this.diskSpace = value;
    }

    /**
     * Gets the value of the postboxs property.
     * 
     */
    public long getPostboxs() {
        return postboxs;
    }

    /**
     * Sets the value of the postboxs property.
     * 
     */
    public void setPostboxs(long value) {
        this.postboxs = value;
    }

    /**
     * Gets the value of the redirects property.
     * 
     */
    public long getRedirects() {
        return redirects;
    }

    /**
     * Sets the value of the redirects property.
     * 
     */
    public void setRedirects(long value) {
        this.redirects = value;
    }

    /**
     * Gets the value of the mailGroups property.
     * 
     */
    public long getMailGroups() {
        return mailGroups;
    }

    /**
     * Sets the value of the mailGroups property.
     * 
     */
    public void setMailGroups(long value) {
        this.mailGroups = value;
    }

    /**
     * Gets the value of the mailResps property.
     * 
     */
    public long getMailResps() {
        return mailResps;
    }

    /**
     * Sets the value of the mailResps property.
     * 
     */
    public void setMailResps(long value) {
        this.mailResps = value;
    }

    /**
     * Gets the value of the mailLists property.
     * 
     */
    public long getMailLists() {
        return mailLists;
    }

    /**
     * Sets the value of the mailLists property.
     * 
     */
    public void setMailLists(long value) {
        this.mailLists = value;
    }

    /**
     * Gets the value of the webUsers property.
     * 
     */
    public long getWebUsers() {
        return webUsers;
    }

    /**
     * Sets the value of the webUsers property.
     * 
     */
    public void setWebUsers(long value) {
        this.webUsers = value;
    }

    /**
     * Gets the value of the dataBases property.
     * 
     */
    public long getDataBases() {
        return dataBases;
    }

    /**
     * Sets the value of the dataBases property.
     * 
     */
    public void setDataBases(long value) {
        this.dataBases = value;
    }

    /**
     * Gets the value of the traffic property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTraffic() {
        return traffic;
    }

    /**
     * Sets the value of the traffic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTraffic(BigInteger value) {
        this.traffic = value;
    }

    /**
     * Gets the value of the trafficPrevday property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrafficPrevday() {
        return trafficPrevday;
    }

    /**
     * Sets the value of the trafficPrevday property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrafficPrevday(BigInteger value) {
        this.trafficPrevday = value;
    }

}
