//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ipType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ipType">
 *   <restriction base="{}string">
 *     <enumeration value="shared"/>
 *     <enumeration value="exclusive"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ipType")
@XmlEnum
public enum IpType {

    @XmlEnumValue("shared")
    SHARED("shared"),
    @XmlEnumValue("exclusive")
    EXCLUSIVE("exclusive");
    private final String value;

    IpType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IpType fromValue(String v) {
        for (IpType c: IpType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
