//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResellerGetInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ResellerGetInput">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="filter" type="{}ResellerSelectionFilter"/>
 *         <element name="dataset" type="{}ResellerDataset"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResellerGetInput", propOrder = {
    "filter",
    "dataset"
})
public class ResellerGetInput {

    @XmlElement(required = true)
    protected ResellerSelectionFilter filter;
    @XmlElement(required = true)
    protected ResellerDataset dataset;

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link ResellerSelectionFilter }
     *     
     */
    public ResellerSelectionFilter getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResellerSelectionFilter }
     *     
     */
    public void setFilter(ResellerSelectionFilter value) {
        this.filter = value;
    }

    /**
     * Gets the value of the dataset property.
     * 
     * @return
     *     possible object is
     *     {@link ResellerDataset }
     *     
     */
    public ResellerDataset getDataset() {
        return dataset;
    }

    /**
     * Sets the value of the dataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResellerDataset }
     *     
     */
    public void setDataset(ResellerDataset value) {
        this.dataset = value;
    }

}
