//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResellerTemplateIpPoolType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ResellerTemplateIpPoolType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ip-address" type="{}ip_address" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="allocate-ip" type="{}int" minOccurs="0"/>
 *         <element name="allocate-ipv6" type="{}int" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResellerTemplateIpPoolType", propOrder = {
    "ipAddress",
    "allocateIp",
    "allocateIpv6"
})
public class ResellerTemplateIpPoolType {

    @XmlElement(name = "ip-address")
    protected List<String> ipAddress;
    @XmlElement(name = "allocate-ip")
    protected BigInteger allocateIp;
    @XmlElement(name = "allocate-ipv6")
    protected BigInteger allocateIpv6;

    /**
     * Gets the value of the ipAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the ipAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the ipAddress property.
     */
    public List<String> getIpAddress() {
        if (ipAddress == null) {
            ipAddress = new ArrayList<>();
        }
        return this.ipAddress;
    }

    /**
     * Gets the value of the allocateIp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllocateIp() {
        return allocateIp;
    }

    /**
     * Sets the value of the allocateIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllocateIp(BigInteger value) {
        this.allocateIp = value;
    }

    /**
     * Gets the value of the allocateIpv6 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllocateIpv6() {
        return allocateIpv6;
    }

    /**
     * Sets the value of the allocateIpv6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllocateIpv6(BigInteger value) {
        this.allocateIpv6 = value;
    }

}
