//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServerOperatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ServerOperatorType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="get_protos" type="{}GetProtosType"/>
 *         <element name="get" type="{}getType"/>
 *         <element name="set" type="{}AdminSetType"/>
 *         <element name="srv_man" type="{}ServicesManagementType"/>
 *         <element name="lic_install" type="{}LicenseInstallType"/>
 *         <element name="lic_update" type="{}LicenseUpdateType"/>
 *         <element name="initial_setup" type="{}initialSetupType"/>
 *         <element name="get_additional_key" type="{}GetAdditionalKeyType"/>
 *         <element name="remove_additional_key" type="{}RemoveAdditionalKeyType"/>
 *         <element name="renew_additional_key" type="{}RenewAdditionalKeyType"/>
 *         <element name="set_misc" type="{}SetMiscType"/>
 *         <element name="get_misc" type="{}GetMiscType"/>
 *         <element name="create_session" type="{}CreateSessionType"/>
 *         <element name="del_misc" type="{}DelMiscType"/>
 *         <element name="set-ppb-connection" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         <element name="reboot" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         <element name="license-rollback-key" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         <element name="license-retrieve-keys" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         <element name="lic_get_info" type="{}LicenseGetInfoType"/>
 *         <element name="clean-mail-queue" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         <element name="add-admin-alias" type="{}AdminAliasAddType"/>
 *         <element name="set-admin-alias" type="{}AdminAliasSetType"/>
 *         <element name="del-admin-alias" type="{}AdminAliasDelType"/>
 *         <element name="domain-restriction-add" type="{}DomainRestrictionAddType"/>
 *         <element name="domain-restriction-remove" type="{}DomainRestrictionRemoveType"/>
 *         <element name="domain-restriction-list" type="{}DomainRestrictionListType"/>
 *         <element name="domain-restriction-rename" type="{}DomainRestrictionRenameType"/>
 *         <element name="domain-restriction-enable" type="{}DomainRestrictionEnableType"/>
 *         <element name="domain-restriction-disable" type="{}DomainRestrictionDisableType"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServerOperatorType", propOrder = {
    "getProtosOrGetOrSet"
})
public class ServerOperatorType {

    @XmlElementRefs({
        @XmlElementRef(name = "get_protos", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "set", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "srv_man", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lic_install", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lic_update", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "initial_setup", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get_additional_key", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remove_additional_key", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "renew_additional_key", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "set_misc", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get_misc", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "create_session", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "del_misc", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "set-ppb-connection", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "reboot", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "license-rollback-key", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "license-retrieve-keys", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lic_get_info", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "clean-mail-queue", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "add-admin-alias", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "set-admin-alias", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "del-admin-alias", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "domain-restriction-add", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "domain-restriction-remove", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "domain-restriction-list", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "domain-restriction-rename", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "domain-restriction-enable", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "domain-restriction-disable", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> getProtosOrGetOrSet;

    /**
     * Gets the value of the getProtosOrGetOrSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the getProtosOrGetOrSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGetProtosOrGetOrSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AdminAliasAddType }{@code >}
     * {@link JAXBElement }{@code <}{@link AdminAliasDelType }{@code >}
     * {@link JAXBElement }{@code <}{@link AdminAliasSetType }{@code >}
     * {@link JAXBElement }{@code <}{@link AdminSetType }{@code >}
     * {@link JAXBElement }{@code <}{@link CreateSessionType }{@code >}
     * {@link JAXBElement }{@code <}{@link DelMiscType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainRestrictionAddType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainRestrictionDisableType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainRestrictionEnableType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainRestrictionListType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainRestrictionRemoveType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainRestrictionRenameType }{@code >}
     * {@link JAXBElement }{@code <}{@link GetAdditionalKeyType }{@code >}
     * {@link JAXBElement }{@code <}{@link GetMiscType }{@code >}
     * {@link JAXBElement }{@code <}{@link GetProtosType }{@code >}
     * {@link JAXBElement }{@code <}{@link GetType }{@code >}
     * {@link JAXBElement }{@code <}{@link InitialSetupType }{@code >}
     * {@link JAXBElement }{@code <}{@link LicenseGetInfoType }{@code >}
     * {@link JAXBElement }{@code <}{@link LicenseInstallType }{@code >}
     * {@link JAXBElement }{@code <}{@link LicenseUpdateType }{@code >}
     * {@link JAXBElement }{@code <}{@link RemoveAdditionalKeyType }{@code >}
     * {@link JAXBElement }{@code <}{@link RenewAdditionalKeyType }{@code >}
     * {@link JAXBElement }{@code <}{@link ServicesManagementType }{@code >}
     * {@link JAXBElement }{@code <}{@link SetMiscType }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     * @return
     *     The value of the getProtosOrGetOrSet property.
     */
    public List<JAXBElement<?>> getGetProtosOrGetOrSet() {
        if (getProtosOrGetOrSet == null) {
            getProtosOrGetOrSet = new ArrayList<>();
        }
        return this.getProtosOrGetOrSet;
    }

}
