//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebspaceDbServerListOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="WebspaceDbServerListOutputType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="result">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{}resultFilterType">
 *                 <sequence minOccurs="0">
 *                   <element name="db-server" type="{}dbServerOutput" maxOccurs="unbounded" minOccurs="0"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebspaceDbServerListOutputType", propOrder = {
    "result"
})
public class WebspaceDbServerListOutputType {

    @XmlElement(required = true)
    protected WebspaceDbServerListOutputType.Result result;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link WebspaceDbServerListOutputType.Result }
     *     
     */
    public WebspaceDbServerListOutputType.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebspaceDbServerListOutputType.Result }
     *     
     */
    public void setResult(WebspaceDbServerListOutputType.Result value) {
        this.result = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{}resultFilterType">
     *       <sequence minOccurs="0">
     *         <element name="db-server" type="{}dbServerOutput" maxOccurs="unbounded" minOccurs="0"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dbServer"
    })
    public static class Result
        extends ResultFilterType
    {

        @XmlElement(name = "db-server")
        protected List<DbServerOutput> dbServer;

        /**
         * Gets the value of the dbServer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the dbServer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDbServer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DbServerOutput }
         * 
         * 
         * @return
         *     The value of the dbServer property.
         */
        public List<DbServerOutput> getDbServer() {
            if (dbServer == null) {
                dbServer = new ArrayList<>();
            }
            return this.dbServer;
        }

    }

}
