//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomainTemplatePHostingPreferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="DomainTemplatePHostingPreferences">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <all minOccurs="0">
 *         <element name="ftp_quota" type="{}int" minOccurs="0"/>
 *         <element name="ssl" type="{}boolean" minOccurs="0"/>
 *         <element name="shell" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{}string">
 *               <maxLength value="255"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="php" type="{}boolean" minOccurs="0"/>
 *         <element name="ssi" type="{}boolean" minOccurs="0"/>
 *         <element name="ssi_html" type="{}boolean" minOccurs="0"/>
 *         <element name="cgi" type="{}boolean" minOccurs="0"/>
 *         <element name="mod_perl" type="{}boolean" minOccurs="0"/>
 *         <element name="mod_python" type="{}boolean" minOccurs="0"/>
 *         <element name="asp" type="{}boolean" minOccurs="0"/>
 *         <element name="asp_dot_net" type="{}boolean" minOccurs="0"/>
 *         <element name="webstat" type="{}webstatType" minOccurs="0"/>
 *         <element name="webstat_protected" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="errdocs" type="{}boolean" minOccurs="0"/>
 *         <element name="at_domains" type="{}boolean" minOccurs="0"/>
 *         <element name="php_safe_mode" type="{}boolean" minOccurs="0"/>
 *         <element name="sb_publishing" type="{}boolean" minOccurs="0"/>
 *         <element name="php_isapi" type="{}boolean" minOccurs="0"/>
 *         <element name="managed_runtime_version" type="{}string" minOccurs="0"/>
 *         <element name="iis-app-pool" type="{}boolean" minOccurs="0"/>
 *         <element name="fastcgi" type="{}boolean" minOccurs="0"/>
 *         <element name="cpu-usage" type="{}int" minOccurs="0"/>
 *         <element name="wuscripts" type="{}boolean" minOccurs="0"/>
 *         <element name="php-version" type="{}string" minOccurs="0"/>
 *         <element name="create-sb-subdomains" type="{}boolean" minOccurs="0"/>
 *       </all>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomainTemplatePHostingPreferences", propOrder = {

})
public class DomainTemplatePHostingPreferences {

    @XmlElement(name = "ftp_quota")
    protected BigInteger ftpQuota;
    protected Boolean ssl;
    @XmlElement(defaultValue = "/bin/false")
    protected String shell;
    protected Boolean php;
    protected Boolean ssi;
    @XmlElement(name = "ssi_html")
    protected Boolean ssiHtml;
    protected Boolean cgi;
    @XmlElement(name = "mod_perl")
    protected Boolean modPerl;
    @XmlElement(name = "mod_python")
    protected Boolean modPython;
    protected Boolean asp;
    @XmlElement(name = "asp_dot_net")
    protected Boolean aspDotNet;
    @XmlSchemaType(name = "string")
    protected WebstatType webstat;
    @XmlElement(name = "webstat_protected")
    protected Boolean webstatProtected;
    protected Boolean errdocs;
    @XmlElement(name = "at_domains")
    protected Boolean atDomains;
    @XmlElement(name = "php_safe_mode")
    protected Boolean phpSafeMode;
    @XmlElement(name = "sb_publishing")
    protected Boolean sbPublishing;
    @XmlElement(name = "php_isapi")
    protected Boolean phpIsapi;
    @XmlElement(name = "managed_runtime_version")
    protected String managedRuntimeVersion;
    @XmlElement(name = "iis-app-pool")
    protected Boolean iisAppPool;
    protected Boolean fastcgi;
    @XmlElement(name = "cpu-usage")
    protected BigInteger cpuUsage;
    protected Boolean wuscripts;
    @XmlElement(name = "php-version")
    protected String phpVersion;
    @XmlElement(name = "create-sb-subdomains")
    protected Boolean createSbSubdomains;

    /**
     * Gets the value of the ftpQuota property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFtpQuota() {
        return ftpQuota;
    }

    /**
     * Sets the value of the ftpQuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFtpQuota(BigInteger value) {
        this.ftpQuota = value;
    }

    /**
     * Gets the value of the ssl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSsl() {
        return ssl;
    }

    /**
     * Sets the value of the ssl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSsl(Boolean value) {
        this.ssl = value;
    }

    /**
     * Gets the value of the shell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShell() {
        return shell;
    }

    /**
     * Sets the value of the shell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShell(String value) {
        this.shell = value;
    }

    /**
     * Gets the value of the php property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPhp() {
        return php;
    }

    /**
     * Sets the value of the php property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPhp(Boolean value) {
        this.php = value;
    }

    /**
     * Gets the value of the ssi property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSsi() {
        return ssi;
    }

    /**
     * Sets the value of the ssi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSsi(Boolean value) {
        this.ssi = value;
    }

    /**
     * Gets the value of the ssiHtml property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSsiHtml() {
        return ssiHtml;
    }

    /**
     * Sets the value of the ssiHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSsiHtml(Boolean value) {
        this.ssiHtml = value;
    }

    /**
     * Gets the value of the cgi property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCgi() {
        return cgi;
    }

    /**
     * Sets the value of the cgi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCgi(Boolean value) {
        this.cgi = value;
    }

    /**
     * Gets the value of the modPerl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isModPerl() {
        return modPerl;
    }

    /**
     * Sets the value of the modPerl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setModPerl(Boolean value) {
        this.modPerl = value;
    }

    /**
     * Gets the value of the modPython property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isModPython() {
        return modPython;
    }

    /**
     * Sets the value of the modPython property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setModPython(Boolean value) {
        this.modPython = value;
    }

    /**
     * Gets the value of the asp property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAsp() {
        return asp;
    }

    /**
     * Sets the value of the asp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAsp(Boolean value) {
        this.asp = value;
    }

    /**
     * Gets the value of the aspDotNet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAspDotNet() {
        return aspDotNet;
    }

    /**
     * Sets the value of the aspDotNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAspDotNet(Boolean value) {
        this.aspDotNet = value;
    }

    /**
     * Gets the value of the webstat property.
     * 
     * @return
     *     possible object is
     *     {@link WebstatType }
     *     
     */
    public WebstatType getWebstat() {
        return webstat;
    }

    /**
     * Sets the value of the webstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebstatType }
     *     
     */
    public void setWebstat(WebstatType value) {
        this.webstat = value;
    }

    /**
     * Gets the value of the webstatProtected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWebstatProtected() {
        return webstatProtected;
    }

    /**
     * Sets the value of the webstatProtected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWebstatProtected(Boolean value) {
        this.webstatProtected = value;
    }

    /**
     * Gets the value of the errdocs property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isErrdocs() {
        return errdocs;
    }

    /**
     * Sets the value of the errdocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setErrdocs(Boolean value) {
        this.errdocs = value;
    }

    /**
     * Gets the value of the atDomains property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAtDomains() {
        return atDomains;
    }

    /**
     * Sets the value of the atDomains property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAtDomains(Boolean value) {
        this.atDomains = value;
    }

    /**
     * Gets the value of the phpSafeMode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPhpSafeMode() {
        return phpSafeMode;
    }

    /**
     * Sets the value of the phpSafeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPhpSafeMode(Boolean value) {
        this.phpSafeMode = value;
    }

    /**
     * Gets the value of the sbPublishing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSbPublishing() {
        return sbPublishing;
    }

    /**
     * Sets the value of the sbPublishing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSbPublishing(Boolean value) {
        this.sbPublishing = value;
    }

    /**
     * Gets the value of the phpIsapi property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPhpIsapi() {
        return phpIsapi;
    }

    /**
     * Sets the value of the phpIsapi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPhpIsapi(Boolean value) {
        this.phpIsapi = value;
    }

    /**
     * Gets the value of the managedRuntimeVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagedRuntimeVersion() {
        return managedRuntimeVersion;
    }

    /**
     * Sets the value of the managedRuntimeVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagedRuntimeVersion(String value) {
        this.managedRuntimeVersion = value;
    }

    /**
     * Gets the value of the iisAppPool property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIisAppPool() {
        return iisAppPool;
    }

    /**
     * Sets the value of the iisAppPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIisAppPool(Boolean value) {
        this.iisAppPool = value;
    }

    /**
     * Gets the value of the fastcgi property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFastcgi() {
        return fastcgi;
    }

    /**
     * Sets the value of the fastcgi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFastcgi(Boolean value) {
        this.fastcgi = value;
    }

    /**
     * Gets the value of the cpuUsage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCpuUsage() {
        return cpuUsage;
    }

    /**
     * Sets the value of the cpuUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCpuUsage(BigInteger value) {
        this.cpuUsage = value;
    }

    /**
     * Gets the value of the wuscripts property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWuscripts() {
        return wuscripts;
    }

    /**
     * Sets the value of the wuscripts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWuscripts(Boolean value) {
        this.wuscripts = value;
    }

    /**
     * Gets the value of the phpVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhpVersion() {
        return phpVersion;
    }

    /**
     * Sets the value of the phpVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhpVersion(String value) {
        this.phpVersion = value;
    }

    /**
     * Gets the value of the createSbSubdomains property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCreateSbSubdomains() {
        return createSbSubdomains;
    }

    /**
     * Sets the value of the createSbSubdomains property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreateSbSubdomains(Boolean value) {
        this.createSbSubdomains = value;
    }

}
