//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetNavigationOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="GetNavigationOutputType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="result">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{}resultType">
 *                 <sequence minOccurs="0">
 *                   <element name="navigation" type="{}string"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetNavigationOutputType", propOrder = {
    "result"
})
public class GetNavigationOutputType {

    @XmlElement(required = true)
    protected GetNavigationOutputType.Result result;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link GetNavigationOutputType.Result }
     *     
     */
    public GetNavigationOutputType.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetNavigationOutputType.Result }
     *     
     */
    public void setResult(GetNavigationOutputType.Result value) {
        this.result = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{}resultType">
     *       <sequence minOccurs="0">
     *         <element name="navigation" type="{}string"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "navigation"
    })
    public static class Result
        extends ResultType
    {

        protected String navigation;

        /**
         * Gets the value of the navigation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNavigation() {
            return navigation;
        }

        /**
         * Sets the value of the navigation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNavigation(String value) {
            this.navigation = value;
        }

    }

}
