//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for operationresultGetInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="operationresultGetInfoType">
 *   <complexContent>
 *     <extension base="{}resultType">
 *       <sequence>
 *         <element name="mailname" type="{}mailnameGetInfoType" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operationresultGetInfoType", propOrder = {
    "mailname"
})
public class OperationresultGetInfoType
    extends ResultType
{

    protected MailnameGetInfoType mailname;

    /**
     * Gets the value of the mailname property.
     * 
     * @return
     *     possible object is
     *     {@link MailnameGetInfoType }
     *     
     */
    public MailnameGetInfoType getMailname() {
        return mailname;
    }

    /**
     * Sets the value of the mailname property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailnameGetInfoType }
     *     
     */
    public void setMailname(MailnameGetInfoType value) {
        this.mailname = value;
    }

}
