//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResellerInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ResellerInput">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="add" type="{}ResellerAddInput"/>
 *         <element name="set" type="{}ResellerSetInput"/>
 *         <element name="get" type="{}ResellerGetInput"/>
 *         <element name="del" type="{}ResellerDelInput"/>
 *         <element name="ippool-add-ip" type="{}ResellerIpPoolOperation"/>
 *         <element name="ippool-del-ip" type="{}ResellerIpPoolDelInput"/>
 *         <element name="ippool-set-ip" type="{}ipPoolResellerSet"/>
 *         <element name="cform-buttons-list">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}ResellerSelectionFilter"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="get-limit-descriptor">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}ResellerSelectionFilter"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="get-permission-descriptor">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}ResellerSelectionFilter"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="convert-to-customer">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}ResellerSelectionFilter"/>
 *                   <element name="plan-name" type="{}string" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="switch-subscription">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}ResellerSelectionFilter"/>
 *                   <choice>
 *                     <element name="plan-guid" type="{}string"/>
 *                     <element name="no-plan" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                     <element name="plan-external-id" type="{}string"/>
 *                   </choice>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="sync-subscription">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}ResellerSelectionFilter"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="add-package" type="{}ResellerApplicationInput"/>
 *         <element name="remove-package" type="{}ResellerApplicationInput"/>
 *         <element name="enable-aps-filter" type="{}ResellerApsFilterTypeInput"/>
 *         <element name="disable-aps-filter" type="{}ResellerApsFilterTypeInput"/>
 *         <element name="get-domain-list">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}ResellerSelectionFilter"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResellerInput", propOrder = {
    "addOrSetOrGet"
})
public class ResellerInput {

    @XmlElementRefs({
        @XmlElementRef(name = "add", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "set", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "del", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ippool-add-ip", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ippool-del-ip", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ippool-set-ip", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cform-buttons-list", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-limit-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-permission-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "convert-to-customer", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "switch-subscription", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sync-subscription", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "add-package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remove-package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "enable-aps-filter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "disable-aps-filter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-domain-list", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> addOrSetOrGet;

    /**
     * Gets the value of the addOrSetOrGet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the addOrSetOrGet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddOrSetOrGet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link IpPoolResellerSet }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerAddInput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerApplicationInput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerApplicationInput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerApsFilterTypeInput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerApsFilterTypeInput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerDelInput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerGetInput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerInput.CformButtonsList }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerInput.ConvertToCustomer }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerInput.GetDomainList }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerInput.GetLimitDescriptor }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerInput.GetPermissionDescriptor }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerInput.SwitchSubscription }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerInput.SyncSubscription }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerIpPoolDelInput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerIpPoolOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerSetInput }{@code >}
     * 
     * 
     * @return
     *     The value of the addOrSetOrGet property.
     */
    public List<JAXBElement<?>> getAddOrSetOrGet() {
        if (addOrSetOrGet == null) {
            addOrSetOrGet = new ArrayList<>();
        }
        return this.addOrSetOrGet;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}ResellerSelectionFilter"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class CformButtonsList {

        @XmlElement(required = true)
        protected ResellerSelectionFilter filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public ResellerSelectionFilter getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public void setFilter(ResellerSelectionFilter value) {
            this.filter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}ResellerSelectionFilter"/>
     *         <element name="plan-name" type="{}string" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter",
        "planName"
    })
    public static class ConvertToCustomer {

        @XmlElement(required = true)
        protected ResellerSelectionFilter filter;
        @XmlElement(name = "plan-name")
        protected String planName;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public ResellerSelectionFilter getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public void setFilter(ResellerSelectionFilter value) {
            this.filter = value;
        }

        /**
         * Gets the value of the planName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanName() {
            return planName;
        }

        /**
         * Sets the value of the planName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanName(String value) {
            this.planName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}ResellerSelectionFilter"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class GetDomainList {

        @XmlElement(required = true)
        protected ResellerSelectionFilter filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public ResellerSelectionFilter getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public void setFilter(ResellerSelectionFilter value) {
            this.filter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}ResellerSelectionFilter"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class GetLimitDescriptor {

        @XmlElement(required = true)
        protected ResellerSelectionFilter filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public ResellerSelectionFilter getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public void setFilter(ResellerSelectionFilter value) {
            this.filter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}ResellerSelectionFilter"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class GetPermissionDescriptor {

        @XmlElement(required = true)
        protected ResellerSelectionFilter filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public ResellerSelectionFilter getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public void setFilter(ResellerSelectionFilter value) {
            this.filter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}ResellerSelectionFilter"/>
     *         <choice>
     *           <element name="plan-guid" type="{}string"/>
     *           <element name="no-plan" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *           <element name="plan-external-id" type="{}string"/>
     *         </choice>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter",
        "planGuid",
        "noPlan",
        "planExternalId"
    })
    public static class SwitchSubscription {

        @XmlElement(required = true)
        protected ResellerSelectionFilter filter;
        @XmlElement(name = "plan-guid")
        protected String planGuid;
        @XmlElement(name = "no-plan")
        protected Object noPlan;
        @XmlElement(name = "plan-external-id")
        protected String planExternalId;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public ResellerSelectionFilter getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public void setFilter(ResellerSelectionFilter value) {
            this.filter = value;
        }

        /**
         * Gets the value of the planGuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanGuid() {
            return planGuid;
        }

        /**
         * Sets the value of the planGuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanGuid(String value) {
            this.planGuid = value;
        }

        /**
         * Gets the value of the noPlan property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getNoPlan() {
            return noPlan;
        }

        /**
         * Sets the value of the noPlan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setNoPlan(Object value) {
            this.noPlan = value;
        }

        /**
         * Gets the value of the planExternalId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanExternalId() {
            return planExternalId;
        }

        /**
         * Sets the value of the planExternalId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanExternalId(String value) {
            this.planExternalId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}ResellerSelectionFilter"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class SyncSubscription {

        @XmlElement(required = true)
        protected ResellerSelectionFilter filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public ResellerSelectionFilter getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResellerSelectionFilter }
         *     
         */
        public void setFilter(ResellerSelectionFilter value) {
            this.filter = value;
        }

    }

}
