//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Information about reseller
 * 
 * <p>Java class for ResellerData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ResellerData">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <all>
 *         <element name="gen-info" type="{}ResellerGetGenInfo" minOccurs="0"/>
 *         <element name="stat" type="{}ResellerStatType" minOccurs="0"/>
 *         <element name="permissions" type="{}clientPerms" minOccurs="0"/>
 *         <element name="limits" type="{}ResellerLimits" minOccurs="0"/>
 *         <element name="ippool" type="{}ipPoolType" minOccurs="0"/>
 *         <element name="subscriptions" type="{}SubscriptionsList" minOccurs="0"/>
 *       </all>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResellerData", propOrder = {

})
public class ResellerData {

    @XmlElement(name = "gen-info")
    protected ResellerGetGenInfo genInfo;
    protected ResellerStatType stat;
    protected ClientPerms permissions;
    protected ResellerLimits limits;
    protected IpPoolType ippool;
    protected SubscriptionsList subscriptions;

    /**
     * Gets the value of the genInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ResellerGetGenInfo }
     *     
     */
    public ResellerGetGenInfo getGenInfo() {
        return genInfo;
    }

    /**
     * Sets the value of the genInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResellerGetGenInfo }
     *     
     */
    public void setGenInfo(ResellerGetGenInfo value) {
        this.genInfo = value;
    }

    /**
     * Gets the value of the stat property.
     * 
     * @return
     *     possible object is
     *     {@link ResellerStatType }
     *     
     */
    public ResellerStatType getStat() {
        return stat;
    }

    /**
     * Sets the value of the stat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResellerStatType }
     *     
     */
    public void setStat(ResellerStatType value) {
        this.stat = value;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link ClientPerms }
     *     
     */
    public ClientPerms getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientPerms }
     *     
     */
    public void setPermissions(ClientPerms value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the limits property.
     * 
     * @return
     *     possible object is
     *     {@link ResellerLimits }
     *     
     */
    public ResellerLimits getLimits() {
        return limits;
    }

    /**
     * Sets the value of the limits property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResellerLimits }
     *     
     */
    public void setLimits(ResellerLimits value) {
        this.limits = value;
    }

    /**
     * Gets the value of the ippool property.
     * 
     * @return
     *     possible object is
     *     {@link IpPoolType }
     *     
     */
    public IpPoolType getIppool() {
        return ippool;
    }

    /**
     * Sets the value of the ippool property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpPoolType }
     *     
     */
    public void setIppool(IpPoolType value) {
        this.ippool = value;
    }

    /**
     * Gets the value of the subscriptions property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionsList }
     *     
     */
    public SubscriptionsList getSubscriptions() {
        return subscriptions;
    }

    /**
     * Sets the value of the subscriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionsList }
     *     
     */
    public void setSubscriptions(SubscriptionsList value) {
        this.subscriptions = value;
    }

}
