//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package generated;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServicePlanAddonApplicationInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ServicePlanAddonApplicationInput">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="filter" type="{}DomainAddonTemplateFilterType"/>
 *         <choice minOccurs="0">
 *           <element name="owner-id" type="{}id_type"/>
 *           <element name="owner-login" type="{}string"/>
 *         </choice>
 *         <element name="package" type="{}ApplicationInput" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServicePlanAddonApplicationInput", propOrder = {
    "filter",
    "ownerId",
    "ownerLogin",
    "_package"
})
public class ServicePlanAddonApplicationInput {

    @XmlElement(required = true)
    protected DomainAddonTemplateFilterType filter;
    @XmlElement(name = "owner-id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ownerId;
    @XmlElement(name = "owner-login")
    protected String ownerLogin;
    @XmlElement(name = "package", required = true)
    protected List<ApplicationInput> _package;

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link DomainAddonTemplateFilterType }
     *     
     */
    public DomainAddonTemplateFilterType getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainAddonTemplateFilterType }
     *     
     */
    public void setFilter(DomainAddonTemplateFilterType value) {
        this.filter = value;
    }

    /**
     * Gets the value of the ownerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOwnerId(BigInteger value) {
        this.ownerId = value;
    }

    /**
     * Gets the value of the ownerLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerLogin() {
        return ownerLogin;
    }

    /**
     * Sets the value of the ownerLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerLogin(String value) {
        this.ownerLogin = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the package property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationInput }
     * 
     * 
     * @return
     *     The value of the package property.
     */
    public List<ApplicationInput> getPackage() {
        if (_package == null) {
            _package = new ArrayList<>();
        }
        return this._package;
    }

}
