//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for APSOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="APSOutputType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="download-package" type="{}APSPackageDownloadOutputType"/>
 *         <element name="get-download-status" type="{}APSPackageDownloadStatusOutputType"/>
 *         <element name="import-package" type="{}APSPackageImportOutputType"/>
 *         <element name="get-packages-list" type="{}APSPackagesListOutputType"/>
 *         <element name="install" type="{}APSInstallOutputType"/>
 *         <element name="import-config" type="{}APSImportConfigOutputType"/>
 *         <element name="set-package-properties" type="{}APSSetPackagesPropertiesOutputType"/>
 *         <element name="get-packages-list-by-reseller" type="{}APSGetPackagesByResellerOutput"/>
 *         <element name="get-packages-list-by-webspace" type="{}APSGetPackagesByWSOutput"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "APSOutputType", propOrder = {
    "downloadPackageOrGetDownloadStatusOrImportPackage"
})
public class APSOutputType {

    @XmlElements({
        @XmlElement(name = "download-package", type = APSPackageDownloadOutputType.class),
        @XmlElement(name = "get-download-status", type = APSPackageDownloadStatusOutputType.class),
        @XmlElement(name = "import-package", type = APSPackageImportOutputType.class),
        @XmlElement(name = "get-packages-list", type = APSPackagesListOutputType.class),
        @XmlElement(name = "install", type = APSInstallOutputType.class),
        @XmlElement(name = "import-config", type = APSImportConfigOutputType.class),
        @XmlElement(name = "set-package-properties", type = APSSetPackagesPropertiesOutputType.class),
        @XmlElement(name = "get-packages-list-by-reseller", type = APSGetPackagesByResellerOutput.class),
        @XmlElement(name = "get-packages-list-by-webspace", type = APSGetPackagesByWSOutput.class)
    })
    protected List<Object> downloadPackageOrGetDownloadStatusOrImportPackage;

    /**
     * Gets the value of the downloadPackageOrGetDownloadStatusOrImportPackage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the downloadPackageOrGetDownloadStatusOrImportPackage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDownloadPackageOrGetDownloadStatusOrImportPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link APSGetPackagesByResellerOutput }
     * {@link APSGetPackagesByWSOutput }
     * {@link APSImportConfigOutputType }
     * {@link APSInstallOutputType }
     * {@link APSPackageDownloadOutputType }
     * {@link APSPackageDownloadStatusOutputType }
     * {@link APSPackageImportOutputType }
     * {@link APSPackagesListOutputType }
     * {@link APSSetPackagesPropertiesOutputType }
     * 
     * 
     * @return
     *     The value of the downloadPackageOrGetDownloadStatusOrImportPackage property.
     */
    public List<Object> getDownloadPackageOrGetDownloadStatusOrImportPackage() {
        if (downloadPackageOrGetDownloadStatusOrImportPackage == null) {
            downloadPackageOrGetDownloadStatusOrImportPackage = new ArrayList<>();
        }
        return this.downloadPackageOrGetDownloadStatusOrImportPackage;
    }

}
