//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for APSPackageDownloadOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="APSPackageDownloadOutputType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="result">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{}resultType">
 *                 <sequence minOccurs="0">
 *                   <element name="task-id" type="{}id_type"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "APSPackageDownloadOutputType", propOrder = {
    "result"
})
public class APSPackageDownloadOutputType {

    @XmlElement(required = true)
    protected APSPackageDownloadOutputType.Result result;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link APSPackageDownloadOutputType.Result }
     *     
     */
    public APSPackageDownloadOutputType.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link APSPackageDownloadOutputType.Result }
     *     
     */
    public void setResult(APSPackageDownloadOutputType.Result value) {
        this.result = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{}resultType">
     *       <sequence minOccurs="0">
     *         <element name="task-id" type="{}id_type"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taskId"
    })
    public static class Result
        extends ResultType
    {

        @XmlElement(name = "task-id")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger taskId;

        /**
         * Gets the value of the taskId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTaskId() {
            return taskId;
        }

        /**
         * Sets the value of the taskId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTaskId(BigInteger value) {
            this.taskId = value;
        }

    }

}
