//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for APSPackageDownloadStatusOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="APSPackageDownloadStatusOutputType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="result" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{}resultFilterType">
 *                 <sequence minOccurs="0">
 *                   <element name="task">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="id" type="{}id_type"/>
 *                             <choice>
 *                               <element name="finished">
 *                                 <complexType>
 *                                   <complexContent>
 *                                     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       <choice>
 *                                         <element name="error" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         <element name="package-id" type="{}id_type"/>
 *                                       </choice>
 *                                     </restriction>
 *                                   </complexContent>
 *                                 </complexType>
 *                               </element>
 *                               <element name="in-progress" type="{}APSPackageDownloadStatusInProgress"/>
 *                             </choice>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "APSPackageDownloadStatusOutputType", propOrder = {
    "result"
})
public class APSPackageDownloadStatusOutputType {

    @XmlElement(required = true)
    protected List<APSPackageDownloadStatusOutputType.Result> result;

    /**
     * Gets the value of the result property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the result property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link APSPackageDownloadStatusOutputType.Result }
     * 
     * 
     * @return
     *     The value of the result property.
     */
    public List<APSPackageDownloadStatusOutputType.Result> getResult() {
        if (result == null) {
            result = new ArrayList<>();
        }
        return this.result;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{}resultFilterType">
     *       <sequence minOccurs="0">
     *         <element name="task">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="id" type="{}id_type"/>
     *                   <choice>
     *                     <element name="finished">
     *                       <complexType>
     *                         <complexContent>
     *                           <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             <choice>
     *                               <element name="error" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               <element name="package-id" type="{}id_type"/>
     *                             </choice>
     *                           </restriction>
     *                         </complexContent>
     *                       </complexType>
     *                     </element>
     *                     <element name="in-progress" type="{}APSPackageDownloadStatusInProgress"/>
     *                   </choice>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "task"
    })
    public static class Result
        extends ResultFilterType
    {

        protected APSPackageDownloadStatusOutputType.Result.Task task;

        /**
         * Gets the value of the task property.
         * 
         * @return
         *     possible object is
         *     {@link APSPackageDownloadStatusOutputType.Result.Task }
         *     
         */
        public APSPackageDownloadStatusOutputType.Result.Task getTask() {
            return task;
        }

        /**
         * Sets the value of the task property.
         * 
         * @param value
         *     allowed object is
         *     {@link APSPackageDownloadStatusOutputType.Result.Task }
         *     
         */
        public void setTask(APSPackageDownloadStatusOutputType.Result.Task value) {
            this.task = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="id" type="{}id_type"/>
         *         <choice>
         *           <element name="finished">
         *             <complexType>
         *               <complexContent>
         *                 <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   <choice>
         *                     <element name="error" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                     <element name="package-id" type="{}id_type"/>
         *                   </choice>
         *                 </restriction>
         *               </complexContent>
         *             </complexType>
         *           </element>
         *           <element name="in-progress" type="{}APSPackageDownloadStatusInProgress"/>
         *         </choice>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "finished",
            "inProgress"
        })
        public static class Task {

            @XmlElement(required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger id;
            protected APSPackageDownloadStatusOutputType.Result.Task.Finished finished;
            @XmlElement(name = "in-progress")
            protected APSPackageDownloadStatusInProgress inProgress;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setId(BigInteger value) {
                this.id = value;
            }

            /**
             * Gets the value of the finished property.
             * 
             * @return
             *     possible object is
             *     {@link APSPackageDownloadStatusOutputType.Result.Task.Finished }
             *     
             */
            public APSPackageDownloadStatusOutputType.Result.Task.Finished getFinished() {
                return finished;
            }

            /**
             * Sets the value of the finished property.
             * 
             * @param value
             *     allowed object is
             *     {@link APSPackageDownloadStatusOutputType.Result.Task.Finished }
             *     
             */
            public void setFinished(APSPackageDownloadStatusOutputType.Result.Task.Finished value) {
                this.finished = value;
            }

            /**
             * Gets the value of the inProgress property.
             * 
             * @return
             *     possible object is
             *     {@link APSPackageDownloadStatusInProgress }
             *     
             */
            public APSPackageDownloadStatusInProgress getInProgress() {
                return inProgress;
            }

            /**
             * Sets the value of the inProgress property.
             * 
             * @param value
             *     allowed object is
             *     {@link APSPackageDownloadStatusInProgress }
             *     
             */
            public void setInProgress(APSPackageDownloadStatusInProgress value) {
                this.inProgress = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       <choice>
             *         <element name="error" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         <element name="package-id" type="{}id_type"/>
             *       </choice>
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "error",
                "packageId"
            })
            public static class Finished {

                protected Object error;
                @XmlElement(name = "package-id")
                @XmlSchemaType(name = "positiveInteger")
                protected BigInteger packageId;

                /**
                 * Gets the value of the error property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getError() {
                    return error;
                }

                /**
                 * Sets the value of the error property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setError(Object value) {
                    this.error = value;
                }

                /**
                 * Gets the value of the packageId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getPackageId() {
                    return packageId;
                }

                /**
                 * Sets the value of the packageId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setPackageId(BigInteger value) {
                    this.packageId = value;
                }

            }

        }

    }

}
