//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DNSRecursionValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="DNSRecursionValueType">
 *   <restriction base="{}string">
 *     <enumeration value="on"/>
 *     <enumeration value="off"/>
 *     <enumeration value="local"/>
 *     <enumeration value="localnets"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "DNSRecursionValueType")
@XmlEnum
public enum DNSRecursionValueType {


    /**
     * Enable dns recursion for all request
     * 
     */
    @XmlEnumValue("on")
    ON("on"),

    /**
     * Disable dns recursion
     * 
     */
    @XmlEnumValue("off")
    OFF("off"),

    /**
     * Enable dns recursion for local request
     * 
     */
    @XmlEnumValue("local")
    LOCAL("local"),
    @XmlEnumValue("localnets")
    LOCALNETS("localnets");
    private final String value;

    DNSRecursionValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DNSRecursionValueType fromValue(String v) {
        for (DNSRecursionValueType c: DNSRecursionValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
