//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Domain Frame Forwarding Hosting
 * 
 * <p>Java class for domainFFHostingBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="domainFFHostingBase">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="dest_url" type="{}forwardingURL"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domainFFHostingBase", propOrder = {
    "destUrl"
})
@XmlSeeAlso({
    generated.DomainHostingAgentGet.FrmFwd.class,
    generated.DomainHostingAgentSet.FrmFwd.class
})
public class DomainFFHostingBase {

    @XmlElement(name = "dest_url", required = true)
    protected String destUrl;

    /**
     * Gets the value of the destUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestUrl() {
        return destUrl;
    }

    /**
     * Sets the value of the destUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestUrl(String value) {
        this.destUrl = value;
    }

}
