//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Fliter domains list
 * 
 * <p>Java class for domainFilterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="domainFilterType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="id" type="{}id_type" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="owner-id" type="{}int" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="name" type="{}string" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="owner-login" type="{}string" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="guid" type="{}string" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="owner-guid" type="{}string" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="external-id" type="{}string" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="owner-external-id" type="{}string" maxOccurs="unbounded" minOccurs="0"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domainFilterType", propOrder = {
    "id",
    "ownerId",
    "name",
    "ownerLogin",
    "guid",
    "ownerGuid",
    "externalId",
    "ownerExternalId"
})
public class DomainFilterType {

    @XmlSchemaType(name = "positiveInteger")
    protected List<BigInteger> id;
    @XmlElement(name = "owner-id")
    protected List<BigInteger> ownerId;
    protected List<String> name;
    @XmlElement(name = "owner-login")
    protected List<String> ownerLogin;
    protected List<String> guid;
    @XmlElement(name = "owner-guid")
    protected List<String> ownerGuid;
    @XmlElement(name = "external-id")
    protected List<String> externalId;
    @XmlElement(name = "owner-external-id")
    protected List<String> ownerExternalId;

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     * @return
     *     The value of the id property.
     */
    public List<BigInteger> getId() {
        if (id == null) {
            id = new ArrayList<>();
        }
        return this.id;
    }

    /**
     * Gets the value of the ownerId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the ownerId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnerId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     * @return
     *     The value of the ownerId property.
     */
    public List<BigInteger> getOwnerId() {
        if (ownerId == null) {
            ownerId = new ArrayList<>();
        }
        return this.ownerId;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the name property.
     */
    public List<String> getName() {
        if (name == null) {
            name = new ArrayList<>();
        }
        return this.name;
    }

    /**
     * Gets the value of the ownerLogin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the ownerLogin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnerLogin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the ownerLogin property.
     */
    public List<String> getOwnerLogin() {
        if (ownerLogin == null) {
            ownerLogin = new ArrayList<>();
        }
        return this.ownerLogin;
    }

    /**
     * Gets the value of the guid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the guid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGuid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the guid property.
     */
    public List<String> getGuid() {
        if (guid == null) {
            guid = new ArrayList<>();
        }
        return this.guid;
    }

    /**
     * Gets the value of the ownerGuid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the ownerGuid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnerGuid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the ownerGuid property.
     */
    public List<String> getOwnerGuid() {
        if (ownerGuid == null) {
            ownerGuid = new ArrayList<>();
        }
        return this.ownerGuid;
    }

    /**
     * Gets the value of the externalId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the externalId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the externalId property.
     */
    public List<String> getExternalId() {
        if (externalId == null) {
            externalId = new ArrayList<>();
        }
        return this.externalId;
    }

    /**
     * Gets the value of the ownerExternalId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the ownerExternalId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnerExternalId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the ownerExternalId property.
     */
    public List<String> getOwnerExternalId() {
        if (ownerExternalId == null) {
            ownerExternalId = new ArrayList<>();
        }
        return this.ownerExternalId;
    }

}
