//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomainAddonTemplateInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="DomainAddonTemplateInputType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="add" type="{}DomainAddonTemplateAddInputType"/>
 *         <element name="get" type="{}DomainAddonTemplateGetInputType"/>
 *         <element name="del" type="{}DomainAddonTemplateDeleteInputType"/>
 *         <element name="set" type="{}DomainAddonTemplateSetInputType"/>
 *         <element name="add-package" type="{}ServicePlanAddonApplicationInput"/>
 *         <element name="remove-package" type="{}ServicePlanAddonApplicationInput"/>
 *         <element name="get-limit-descriptor" type="{}DomainAddonTemplateGetInputType"/>
 *         <element name="get-permission-descriptor" type="{}DomainAddonTemplateGetInputType"/>
 *         <element name="get-physical-hosting-descriptor" type="{}DomainAddonTemplateGetInputType"/>
 *         <element name="duplicate" type="{}DomainAddonTemplateDuplicateInputType"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomainAddonTemplateInputType", propOrder = {
    "addOrGetOrDel"
})
public class DomainAddonTemplateInputType {

    @XmlElementRefs({
        @XmlElementRef(name = "add", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "del", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "set", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "add-package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remove-package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-limit-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-permission-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-physical-hosting-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "duplicate", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> addOrGetOrDel;

    /**
     * Gets the value of the addOrGetOrDel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the addOrGetOrDel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddOrGetOrDel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link DomainAddonTemplateAddInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainAddonTemplateDeleteInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainAddonTemplateDuplicateInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainAddonTemplateGetInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainAddonTemplateGetInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainAddonTemplateGetInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainAddonTemplateGetInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainAddonTemplateSetInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link ServicePlanAddonApplicationInput }{@code >}
     * {@link JAXBElement }{@code <}{@link ServicePlanAddonApplicationInput }{@code >}
     * 
     * 
     * @return
     *     The value of the addOrGetOrDel property.
     */
    public List<JAXBElement<?>> getAddOrGetOrDel() {
        if (addOrGetOrDel == null) {
            addOrGetOrDel = new ArrayList<>();
        }
        return this.addOrGetOrDel;
    }

}
