//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.math.BigInteger;
import java.util.ArrayList;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomainTypeRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="DomainTypeRequest">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="add">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="gen_setup">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <choice maxOccurs="10">
 *                             <element name="name" type="{}domainName"/>
 *                             <choice minOccurs="0">
 *                               <element name="owner-id" type="{}int" minOccurs="0"/>
 *                               <element name="owner-login" type="{}string" minOccurs="0"/>
 *                               <element name="owner-guid" type="{}string" minOccurs="0"/>
 *                               <element name="owner-external-id" type="{}string" minOccurs="0"/>
 *                             </choice>
 *                             <element name="htype" type="{}domainHType" minOccurs="0"/>
 *                             <element name="ip_address" type="{}ip_address" minOccurs="0"/>
 *                             <element name="status" type="{}string" minOccurs="0"/>
 *                             <element name="external-id" type="{}string" minOccurs="0"/>
 *                             <element name="description" type="{}string" minOccurs="0"/>
 *                             <element name="admin-description" type="{}string" minOccurs="0"/>
 *                             <element name="reseller-description" type="{}string" minOccurs="0"/>
 *                           </choice>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="hosting" type="{}domainHostingAgentSet" minOccurs="0"/>
 *                   <element name="limits" type="{}domainLimits" minOccurs="0"/>
 *                   <element name="prefs" type="{}domainPrefs" minOccurs="0"/>
 *                   <element name="performance" type="{}DomainPerformanceType" minOccurs="0"/>
 *                   <element name="permissions" type="{}domainPerms" minOccurs="0"/>
 *                   <element name="php-settings" type="{}phpSettings" minOccurs="0"/>
 *                   <choice minOccurs="0">
 *                     <element name="plan-id" type="{}id_type"/>
 *                     <element name="plan-name" type="{}string"/>
 *                     <element name="plan-guid" type="{}string"/>
 *                     <element name="plan-external-id" type="{}string"/>
 *                   </choice>
 *                   <element name="mail" type="{}WebspaceMailPreferences" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="get">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                   <element name="dataset" type="{}domainDatasetType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="set">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                   <element name="values">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="gen_setup" type="{}setGenSetupType" minOccurs="0"/>
 *                             <element name="limits" type="{}domainLimits" minOccurs="0"/>
 *                             <element name="prefs" type="{}domainPrefs" minOccurs="0"/>
 *                             <element name="hosting" type="{}domainHostingAgentSet" minOccurs="0"/>
 *                             <element name="disk_usage" minOccurs="0">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     <sequence>
 *                                       <element name="mailboxes" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                                       <element name="maillists" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                                     </sequence>
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                             <element name="performance" type="{}DomainPerformanceType" minOccurs="0"/>
 *                             <element name="permissions" type="{}domainPerms" minOccurs="0"/>
 *                             <element name="php-settings" type="{}phpSettings" minOccurs="0"/>
 *                             <element name="mail" type="{}WebspaceMailPreferences" minOccurs="0"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="del">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="cform_buttons_list">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="get_traffic">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                   <element name="since_date" type="{}date" minOccurs="0"/>
 *                   <element name="to_date" type="{}date" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="set_traffic">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="dom_id" type="{}int"/>
 *                   <element name="date" type="{}date"/>
 *                   <element name="smtp_in" type="{}long"/>
 *                   <element name="smtp_out" type="{}long"/>
 *                   <element name="pop3_imap_in" type="{}long"/>
 *                   <element name="pop3_imap_out" type="{}long"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="get-limit-descriptor">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="get-permission-descriptor">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="get-physical-hosting-descriptor">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="switch-subscription">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                   <choice>
 *                     <element name="plan-guid" type="{}string"/>
 *                     <element name="plan-external-id" type="{}string"/>
 *                     <element name="no-plan" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   </choice>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="sync-subscription">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="add-subscription">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                   <choice>
 *                     <element name="plan-guid" type="{}string"/>
 *                     <element name="plan-external-id" type="{}string"/>
 *                   </choice>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="remove-subscription">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="filter" type="{}domainFilterType"/>
 *                   <choice>
 *                     <element name="plan-guid" type="{}string"/>
 *                     <element name="plan-external-id" type="{}string"/>
 *                   </choice>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="add-package" type="{}WebspaceApplicationInput"/>
 *         <element name="remove-package" type="{}WebspaceApplicationInput"/>
 *         <element name="add-plan-item" type="{}WebspacePlanItemInputType"/>
 *         <element name="remove-plan-item" type="{}WebspacePlanItemInputType"/>
 *         <element name="enable-aps-filter" type="{}WebspaceApsFilterInputType"/>
 *         <element name="disable-aps-filter" type="{}WebspaceApsFilterInputType"/>
 *         <element name="get-changed">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="resource-usage">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="from" type="{}datetime"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="db-servers">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element name="add" type="{}WebspaceDbServerInput"/>
 *                   <element name="remove" type="{}WebspaceDbServerInput"/>
 *                   <element name="list">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="filter" type="{}domainFilterType"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </choice>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomainTypeRequest", propOrder = {
    "addOrGetOrSet"
})
public class DomainTypeRequest {

    @XmlElementRefs({
        @XmlElementRef(name = "add", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "set", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "del", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cform_buttons_list", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get_traffic", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "set_traffic", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-limit-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-permission-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-physical-hosting-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "switch-subscription", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sync-subscription", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "add-subscription", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remove-subscription", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "add-package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remove-package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "add-plan-item", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remove-plan-item", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "enable-aps-filter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "disable-aps-filter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-changed", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "db-servers", type = JAXBElement.class, required = false)
    })
    protected java.util.List<JAXBElement<?>> addOrGetOrSet;

    /**
     * Gets the value of the addOrGetOrSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the addOrGetOrSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddOrGetOrSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.Add }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.AddSubscription }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.CformButtonsList }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.DbServers }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.Del }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.Get }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.GetChanged }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.GetLimitDescriptor }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.GetPermissionDescriptor }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.GetPhysicalHostingDescriptor }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.GetTraffic }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.RemoveSubscription }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.Set }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.SetTraffic }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.SwitchSubscription }{@code >}
     * {@link JAXBElement }{@code <}{@link DomainTypeRequest.SyncSubscription }{@code >}
     * {@link JAXBElement }{@code <}{@link WebspaceApplicationInput }{@code >}
     * {@link JAXBElement }{@code <}{@link WebspaceApplicationInput }{@code >}
     * {@link JAXBElement }{@code <}{@link WebspaceApsFilterInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link WebspaceApsFilterInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link WebspacePlanItemInputType }{@code >}
     * {@link JAXBElement }{@code <}{@link WebspacePlanItemInputType }{@code >}
     * 
     * 
     * @return
     *     The value of the addOrGetOrSet property.
     */
    public java.util.List<JAXBElement<?>> getAddOrGetOrSet() {
        if (addOrGetOrSet == null) {
            addOrGetOrSet = new ArrayList<>();
        }
        return this.addOrGetOrSet;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="gen_setup">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <choice maxOccurs="10">
     *                   <element name="name" type="{}domainName"/>
     *                   <choice minOccurs="0">
     *                     <element name="owner-id" type="{}int" minOccurs="0"/>
     *                     <element name="owner-login" type="{}string" minOccurs="0"/>
     *                     <element name="owner-guid" type="{}string" minOccurs="0"/>
     *                     <element name="owner-external-id" type="{}string" minOccurs="0"/>
     *                   </choice>
     *                   <element name="htype" type="{}domainHType" minOccurs="0"/>
     *                   <element name="ip_address" type="{}ip_address" minOccurs="0"/>
     *                   <element name="status" type="{}string" minOccurs="0"/>
     *                   <element name="external-id" type="{}string" minOccurs="0"/>
     *                   <element name="description" type="{}string" minOccurs="0"/>
     *                   <element name="admin-description" type="{}string" minOccurs="0"/>
     *                   <element name="reseller-description" type="{}string" minOccurs="0"/>
     *                 </choice>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="hosting" type="{}domainHostingAgentSet" minOccurs="0"/>
     *         <element name="limits" type="{}domainLimits" minOccurs="0"/>
     *         <element name="prefs" type="{}domainPrefs" minOccurs="0"/>
     *         <element name="performance" type="{}DomainPerformanceType" minOccurs="0"/>
     *         <element name="permissions" type="{}domainPerms" minOccurs="0"/>
     *         <element name="php-settings" type="{}phpSettings" minOccurs="0"/>
     *         <choice minOccurs="0">
     *           <element name="plan-id" type="{}id_type"/>
     *           <element name="plan-name" type="{}string"/>
     *           <element name="plan-guid" type="{}string"/>
     *           <element name="plan-external-id" type="{}string"/>
     *         </choice>
     *         <element name="mail" type="{}WebspaceMailPreferences" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "genSetup",
        "hosting",
        "limits",
        "prefs",
        "performance",
        "permissions",
        "phpSettings",
        "planId",
        "planName",
        "planGuid",
        "planExternalId",
        "mail"
    })
    public static class Add {

        @XmlElement(name = "gen_setup", required = true)
        protected DomainTypeRequest.Add.GenSetup genSetup;
        protected DomainHostingAgentSet hosting;
        protected DomainLimits limits;
        protected DomainPrefs prefs;
        protected DomainPerformanceType performance;
        protected DomainPerms permissions;
        @XmlElement(name = "php-settings")
        protected PhpSettings phpSettings;
        @XmlElement(name = "plan-id")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger planId;
        @XmlElement(name = "plan-name")
        protected String planName;
        @XmlElement(name = "plan-guid")
        protected String planGuid;
        @XmlElement(name = "plan-external-id")
        protected String planExternalId;
        protected WebspaceMailPreferences mail;

        /**
         * Gets the value of the genSetup property.
         * 
         * @return
         *     possible object is
         *     {@link DomainTypeRequest.Add.GenSetup }
         *     
         */
        public DomainTypeRequest.Add.GenSetup getGenSetup() {
            return genSetup;
        }

        /**
         * Sets the value of the genSetup property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainTypeRequest.Add.GenSetup }
         *     
         */
        public void setGenSetup(DomainTypeRequest.Add.GenSetup value) {
            this.genSetup = value;
        }

        /**
         * Gets the value of the hosting property.
         * 
         * @return
         *     possible object is
         *     {@link DomainHostingAgentSet }
         *     
         */
        public DomainHostingAgentSet getHosting() {
            return hosting;
        }

        /**
         * Sets the value of the hosting property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainHostingAgentSet }
         *     
         */
        public void setHosting(DomainHostingAgentSet value) {
            this.hosting = value;
        }

        /**
         * Gets the value of the limits property.
         * 
         * @return
         *     possible object is
         *     {@link DomainLimits }
         *     
         */
        public DomainLimits getLimits() {
            return limits;
        }

        /**
         * Sets the value of the limits property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainLimits }
         *     
         */
        public void setLimits(DomainLimits value) {
            this.limits = value;
        }

        /**
         * Gets the value of the prefs property.
         * 
         * @return
         *     possible object is
         *     {@link DomainPrefs }
         *     
         */
        public DomainPrefs getPrefs() {
            return prefs;
        }

        /**
         * Sets the value of the prefs property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainPrefs }
         *     
         */
        public void setPrefs(DomainPrefs value) {
            this.prefs = value;
        }

        /**
         * Gets the value of the performance property.
         * 
         * @return
         *     possible object is
         *     {@link DomainPerformanceType }
         *     
         */
        public DomainPerformanceType getPerformance() {
            return performance;
        }

        /**
         * Sets the value of the performance property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainPerformanceType }
         *     
         */
        public void setPerformance(DomainPerformanceType value) {
            this.performance = value;
        }

        /**
         * Gets the value of the permissions property.
         * 
         * @return
         *     possible object is
         *     {@link DomainPerms }
         *     
         */
        public DomainPerms getPermissions() {
            return permissions;
        }

        /**
         * Sets the value of the permissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainPerms }
         *     
         */
        public void setPermissions(DomainPerms value) {
            this.permissions = value;
        }

        /**
         * Gets the value of the phpSettings property.
         * 
         * @return
         *     possible object is
         *     {@link PhpSettings }
         *     
         */
        public PhpSettings getPhpSettings() {
            return phpSettings;
        }

        /**
         * Sets the value of the phpSettings property.
         * 
         * @param value
         *     allowed object is
         *     {@link PhpSettings }
         *     
         */
        public void setPhpSettings(PhpSettings value) {
            this.phpSettings = value;
        }

        /**
         * Gets the value of the planId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPlanId() {
            return planId;
        }

        /**
         * Sets the value of the planId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPlanId(BigInteger value) {
            this.planId = value;
        }

        /**
         * Gets the value of the planName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanName() {
            return planName;
        }

        /**
         * Sets the value of the planName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanName(String value) {
            this.planName = value;
        }

        /**
         * Gets the value of the planGuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanGuid() {
            return planGuid;
        }

        /**
         * Sets the value of the planGuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanGuid(String value) {
            this.planGuid = value;
        }

        /**
         * Gets the value of the planExternalId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanExternalId() {
            return planExternalId;
        }

        /**
         * Sets the value of the planExternalId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanExternalId(String value) {
            this.planExternalId = value;
        }

        /**
         * Gets the value of the mail property.
         * 
         * @return
         *     possible object is
         *     {@link WebspaceMailPreferences }
         *     
         */
        public WebspaceMailPreferences getMail() {
            return mail;
        }

        /**
         * Sets the value of the mail property.
         * 
         * @param value
         *     allowed object is
         *     {@link WebspaceMailPreferences }
         *     
         */
        public void setMail(WebspaceMailPreferences value) {
            this.mail = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <choice maxOccurs="10">
         *         <element name="name" type="{}domainName"/>
         *         <choice minOccurs="0">
         *           <element name="owner-id" type="{}int" minOccurs="0"/>
         *           <element name="owner-login" type="{}string" minOccurs="0"/>
         *           <element name="owner-guid" type="{}string" minOccurs="0"/>
         *           <element name="owner-external-id" type="{}string" minOccurs="0"/>
         *         </choice>
         *         <element name="htype" type="{}domainHType" minOccurs="0"/>
         *         <element name="ip_address" type="{}ip_address" minOccurs="0"/>
         *         <element name="status" type="{}string" minOccurs="0"/>
         *         <element name="external-id" type="{}string" minOccurs="0"/>
         *         <element name="description" type="{}string" minOccurs="0"/>
         *         <element name="admin-description" type="{}string" minOccurs="0"/>
         *         <element name="reseller-description" type="{}string" minOccurs="0"/>
         *       </choice>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nameOrOwnerIdOrOwnerLogin"
        })
        public static class GenSetup {

            @XmlElementRefs({
                @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "owner-id", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "owner-login", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "owner-guid", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "owner-external-id", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "htype", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "ip_address", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "status", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "external-id", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "description", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "admin-description", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "reseller-description", type = JAXBElement.class, required = false)
            })
            protected java.util.List<JAXBElement<?>> nameOrOwnerIdOrOwnerLogin;

            /**
             * Gets the value of the nameOrOwnerIdOrOwnerLogin property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a {@code set} method for the nameOrOwnerIdOrOwnerLogin property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getNameOrOwnerIdOrOwnerLogin().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link DomainHType }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * 
             * 
             * @return
             *     The value of the nameOrOwnerIdOrOwnerLogin property.
             */
            public java.util.List<JAXBElement<?>> getNameOrOwnerIdOrOwnerLogin() {
                if (nameOrOwnerIdOrOwnerLogin == null) {
                    nameOrOwnerIdOrOwnerLogin = new ArrayList<>();
                }
                return this.nameOrOwnerIdOrOwnerLogin;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *         <choice>
     *           <element name="plan-guid" type="{}string"/>
     *           <element name="plan-external-id" type="{}string"/>
     *         </choice>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter",
        "planGuid",
        "planExternalId"
    })
    public static class AddSubscription {

        @XmlElement(required = true)
        protected DomainFilterType filter;
        @XmlElement(name = "plan-guid")
        protected String planGuid;
        @XmlElement(name = "plan-external-id")
        protected String planExternalId;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

        /**
         * Gets the value of the planGuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanGuid() {
            return planGuid;
        }

        /**
         * Sets the value of the planGuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanGuid(String value) {
            this.planGuid = value;
        }

        /**
         * Gets the value of the planExternalId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanExternalId() {
            return planExternalId;
        }

        /**
         * Sets the value of the planExternalId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanExternalId(String value) {
            this.planExternalId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class CformButtonsList {

        @XmlElement(required = true)
        protected DomainFilterType filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element name="add" type="{}WebspaceDbServerInput"/>
     *         <element name="remove" type="{}WebspaceDbServerInput"/>
     *         <element name="list">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="filter" type="{}domainFilterType"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </choice>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "add",
        "remove",
        "list"
    })
    public static class DbServers {

        protected WebspaceDbServerInput add;
        protected WebspaceDbServerInput remove;
        protected DomainTypeRequest.DbServers.List list;

        /**
         * Gets the value of the add property.
         * 
         * @return
         *     possible object is
         *     {@link WebspaceDbServerInput }
         *     
         */
        public WebspaceDbServerInput getAdd() {
            return add;
        }

        /**
         * Sets the value of the add property.
         * 
         * @param value
         *     allowed object is
         *     {@link WebspaceDbServerInput }
         *     
         */
        public void setAdd(WebspaceDbServerInput value) {
            this.add = value;
        }

        /**
         * Gets the value of the remove property.
         * 
         * @return
         *     possible object is
         *     {@link WebspaceDbServerInput }
         *     
         */
        public WebspaceDbServerInput getRemove() {
            return remove;
        }

        /**
         * Sets the value of the remove property.
         * 
         * @param value
         *     allowed object is
         *     {@link WebspaceDbServerInput }
         *     
         */
        public void setRemove(WebspaceDbServerInput value) {
            this.remove = value;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link DomainTypeRequest.DbServers.List }
         *     
         */
        public DomainTypeRequest.DbServers.List getList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainTypeRequest.DbServers.List }
         *     
         */
        public void setList(DomainTypeRequest.DbServers.List value) {
            this.list = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="filter" type="{}domainFilterType"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "filter"
        })
        public static class List {

            @XmlElement(required = true)
            protected DomainFilterType filter;

            /**
             * Gets the value of the filter property.
             * 
             * @return
             *     possible object is
             *     {@link DomainFilterType }
             *     
             */
            public DomainFilterType getFilter() {
                return filter;
            }

            /**
             * Sets the value of the filter property.
             * 
             * @param value
             *     allowed object is
             *     {@link DomainFilterType }
             *     
             */
            public void setFilter(DomainFilterType value) {
                this.filter = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class Del {

        @XmlElement(required = true)
        protected DomainFilterType filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *         <element name="dataset" type="{}domainDatasetType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter",
        "dataset"
    })
    public static class Get {

        @XmlElement(required = true)
        protected DomainFilterType filter;
        @XmlElement(required = true)
        protected DomainDatasetType dataset;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

        /**
         * Gets the value of the dataset property.
         * 
         * @return
         *     possible object is
         *     {@link DomainDatasetType }
         *     
         */
        public DomainDatasetType getDataset() {
            return dataset;
        }

        /**
         * Sets the value of the dataset property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainDatasetType }
         *     
         */
        public void setDataset(DomainDatasetType value) {
            this.dataset = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="resource-usage">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="from" type="{}datetime"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resourceUsage"
    })
    public static class GetChanged {

        @XmlElement(name = "resource-usage", required = true)
        protected DomainTypeRequest.GetChanged.ResourceUsage resourceUsage;

        /**
         * Gets the value of the resourceUsage property.
         * 
         * @return
         *     possible object is
         *     {@link DomainTypeRequest.GetChanged.ResourceUsage }
         *     
         */
        public DomainTypeRequest.GetChanged.ResourceUsage getResourceUsage() {
            return resourceUsage;
        }

        /**
         * Sets the value of the resourceUsage property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainTypeRequest.GetChanged.ResourceUsage }
         *     
         */
        public void setResourceUsage(DomainTypeRequest.GetChanged.ResourceUsage value) {
            this.resourceUsage = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="from" type="{}datetime"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "from"
        })
        public static class ResourceUsage {

            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar from;

            /**
             * Gets the value of the from property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFrom() {
                return from;
            }

            /**
             * Sets the value of the from property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFrom(XMLGregorianCalendar value) {
                this.from = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class GetLimitDescriptor {

        @XmlElement(required = true)
        protected DomainFilterType filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class GetPermissionDescriptor {

        @XmlElement(required = true)
        protected DomainFilterType filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class GetPhysicalHostingDescriptor {

        @XmlElement(required = true)
        protected DomainFilterType filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *         <element name="since_date" type="{}date" minOccurs="0"/>
     *         <element name="to_date" type="{}date" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter",
        "sinceDate",
        "toDate"
    })
    public static class GetTraffic {

        @XmlElement(required = true)
        protected DomainFilterType filter;
        @XmlElement(name = "since_date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar sinceDate;
        @XmlElement(name = "to_date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar toDate;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

        /**
         * Gets the value of the sinceDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getSinceDate() {
            return sinceDate;
        }

        /**
         * Sets the value of the sinceDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setSinceDate(XMLGregorianCalendar value) {
            this.sinceDate = value;
        }

        /**
         * Gets the value of the toDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getToDate() {
            return toDate;
        }

        /**
         * Sets the value of the toDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setToDate(XMLGregorianCalendar value) {
            this.toDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *         <choice>
     *           <element name="plan-guid" type="{}string"/>
     *           <element name="plan-external-id" type="{}string"/>
     *         </choice>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter",
        "planGuid",
        "planExternalId"
    })
    public static class RemoveSubscription {

        @XmlElement(required = true)
        protected DomainFilterType filter;
        @XmlElement(name = "plan-guid")
        protected String planGuid;
        @XmlElement(name = "plan-external-id")
        protected String planExternalId;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

        /**
         * Gets the value of the planGuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanGuid() {
            return planGuid;
        }

        /**
         * Sets the value of the planGuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanGuid(String value) {
            this.planGuid = value;
        }

        /**
         * Gets the value of the planExternalId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanExternalId() {
            return planExternalId;
        }

        /**
         * Sets the value of the planExternalId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanExternalId(String value) {
            this.planExternalId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *         <element name="values">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="gen_setup" type="{}setGenSetupType" minOccurs="0"/>
     *                   <element name="limits" type="{}domainLimits" minOccurs="0"/>
     *                   <element name="prefs" type="{}domainPrefs" minOccurs="0"/>
     *                   <element name="hosting" type="{}domainHostingAgentSet" minOccurs="0"/>
     *                   <element name="disk_usage" minOccurs="0">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           <sequence>
     *                             <element name="mailboxes" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                             <element name="maillists" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                           </sequence>
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                   <element name="performance" type="{}DomainPerformanceType" minOccurs="0"/>
     *                   <element name="permissions" type="{}domainPerms" minOccurs="0"/>
     *                   <element name="php-settings" type="{}phpSettings" minOccurs="0"/>
     *                   <element name="mail" type="{}WebspaceMailPreferences" minOccurs="0"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter",
        "values"
    })
    public static class Set {

        @XmlElement(required = true)
        protected DomainFilterType filter;
        @XmlElement(required = true)
        protected DomainTypeRequest.Set.Values values;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

        /**
         * Gets the value of the values property.
         * 
         * @return
         *     possible object is
         *     {@link DomainTypeRequest.Set.Values }
         *     
         */
        public DomainTypeRequest.Set.Values getValues() {
            return values;
        }

        /**
         * Sets the value of the values property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainTypeRequest.Set.Values }
         *     
         */
        public void setValues(DomainTypeRequest.Set.Values value) {
            this.values = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="gen_setup" type="{}setGenSetupType" minOccurs="0"/>
         *         <element name="limits" type="{}domainLimits" minOccurs="0"/>
         *         <element name="prefs" type="{}domainPrefs" minOccurs="0"/>
         *         <element name="hosting" type="{}domainHostingAgentSet" minOccurs="0"/>
         *         <element name="disk_usage" minOccurs="0">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 <sequence>
         *                   <element name="mailboxes" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *                   <element name="maillists" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *                 </sequence>
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *         <element name="performance" type="{}DomainPerformanceType" minOccurs="0"/>
         *         <element name="permissions" type="{}domainPerms" minOccurs="0"/>
         *         <element name="php-settings" type="{}phpSettings" minOccurs="0"/>
         *         <element name="mail" type="{}WebspaceMailPreferences" minOccurs="0"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "genSetup",
            "limits",
            "prefs",
            "hosting",
            "diskUsage",
            "performance",
            "permissions",
            "phpSettings",
            "mail"
        })
        public static class Values {

            @XmlElement(name = "gen_setup")
            protected SetGenSetupType genSetup;
            protected DomainLimits limits;
            protected DomainPrefs prefs;
            protected DomainHostingAgentSet hosting;
            @XmlElement(name = "disk_usage")
            protected DomainTypeRequest.Set.Values.DiskUsage diskUsage;
            protected DomainPerformanceType performance;
            protected DomainPerms permissions;
            @XmlElement(name = "php-settings")
            protected PhpSettings phpSettings;
            protected WebspaceMailPreferences mail;

            /**
             * Gets the value of the genSetup property.
             * 
             * @return
             *     possible object is
             *     {@link SetGenSetupType }
             *     
             */
            public SetGenSetupType getGenSetup() {
                return genSetup;
            }

            /**
             * Sets the value of the genSetup property.
             * 
             * @param value
             *     allowed object is
             *     {@link SetGenSetupType }
             *     
             */
            public void setGenSetup(SetGenSetupType value) {
                this.genSetup = value;
            }

            /**
             * Gets the value of the limits property.
             * 
             * @return
             *     possible object is
             *     {@link DomainLimits }
             *     
             */
            public DomainLimits getLimits() {
                return limits;
            }

            /**
             * Sets the value of the limits property.
             * 
             * @param value
             *     allowed object is
             *     {@link DomainLimits }
             *     
             */
            public void setLimits(DomainLimits value) {
                this.limits = value;
            }

            /**
             * Gets the value of the prefs property.
             * 
             * @return
             *     possible object is
             *     {@link DomainPrefs }
             *     
             */
            public DomainPrefs getPrefs() {
                return prefs;
            }

            /**
             * Sets the value of the prefs property.
             * 
             * @param value
             *     allowed object is
             *     {@link DomainPrefs }
             *     
             */
            public void setPrefs(DomainPrefs value) {
                this.prefs = value;
            }

            /**
             * Gets the value of the hosting property.
             * 
             * @return
             *     possible object is
             *     {@link DomainHostingAgentSet }
             *     
             */
            public DomainHostingAgentSet getHosting() {
                return hosting;
            }

            /**
             * Sets the value of the hosting property.
             * 
             * @param value
             *     allowed object is
             *     {@link DomainHostingAgentSet }
             *     
             */
            public void setHosting(DomainHostingAgentSet value) {
                this.hosting = value;
            }

            /**
             * Gets the value of the diskUsage property.
             * 
             * @return
             *     possible object is
             *     {@link DomainTypeRequest.Set.Values.DiskUsage }
             *     
             */
            public DomainTypeRequest.Set.Values.DiskUsage getDiskUsage() {
                return diskUsage;
            }

            /**
             * Sets the value of the diskUsage property.
             * 
             * @param value
             *     allowed object is
             *     {@link DomainTypeRequest.Set.Values.DiskUsage }
             *     
             */
            public void setDiskUsage(DomainTypeRequest.Set.Values.DiskUsage value) {
                this.diskUsage = value;
            }

            /**
             * Gets the value of the performance property.
             * 
             * @return
             *     possible object is
             *     {@link DomainPerformanceType }
             *     
             */
            public DomainPerformanceType getPerformance() {
                return performance;
            }

            /**
             * Sets the value of the performance property.
             * 
             * @param value
             *     allowed object is
             *     {@link DomainPerformanceType }
             *     
             */
            public void setPerformance(DomainPerformanceType value) {
                this.performance = value;
            }

            /**
             * Gets the value of the permissions property.
             * 
             * @return
             *     possible object is
             *     {@link DomainPerms }
             *     
             */
            public DomainPerms getPermissions() {
                return permissions;
            }

            /**
             * Sets the value of the permissions property.
             * 
             * @param value
             *     allowed object is
             *     {@link DomainPerms }
             *     
             */
            public void setPermissions(DomainPerms value) {
                this.permissions = value;
            }

            /**
             * Gets the value of the phpSettings property.
             * 
             * @return
             *     possible object is
             *     {@link PhpSettings }
             *     
             */
            public PhpSettings getPhpSettings() {
                return phpSettings;
            }

            /**
             * Sets the value of the phpSettings property.
             * 
             * @param value
             *     allowed object is
             *     {@link PhpSettings }
             *     
             */
            public void setPhpSettings(PhpSettings value) {
                this.phpSettings = value;
            }

            /**
             * Gets the value of the mail property.
             * 
             * @return
             *     possible object is
             *     {@link WebspaceMailPreferences }
             *     
             */
            public WebspaceMailPreferences getMail() {
                return mail;
            }

            /**
             * Sets the value of the mail property.
             * 
             * @param value
             *     allowed object is
             *     {@link WebspaceMailPreferences }
             *     
             */
            public void setMail(WebspaceMailPreferences value) {
                this.mail = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       <sequence>
             *         <element name="mailboxes" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
             *         <element name="maillists" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
             *       </sequence>
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "mailboxes",
                "maillists"
            })
            public static class DiskUsage {

                protected Object mailboxes;
                protected Object maillists;

                /**
                 * Gets the value of the mailboxes property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getMailboxes() {
                    return mailboxes;
                }

                /**
                 * Sets the value of the mailboxes property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setMailboxes(Object value) {
                    this.mailboxes = value;
                }

                /**
                 * Gets the value of the maillists property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getMaillists() {
                    return maillists;
                }

                /**
                 * Sets the value of the maillists property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setMaillists(Object value) {
                    this.maillists = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="dom_id" type="{}int"/>
     *         <element name="date" type="{}date"/>
     *         <element name="smtp_in" type="{}long"/>
     *         <element name="smtp_out" type="{}long"/>
     *         <element name="pop3_imap_in" type="{}long"/>
     *         <element name="pop3_imap_out" type="{}long"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "domId",
        "date",
        "smtpIn",
        "smtpOut",
        "pop3ImapIn",
        "pop3ImapOut"
    })
    public static class SetTraffic {

        @XmlElement(name = "dom_id", required = true)
        protected BigInteger domId;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "smtp_in")
        protected long smtpIn;
        @XmlElement(name = "smtp_out")
        protected long smtpOut;
        @XmlElement(name = "pop3_imap_in")
        protected long pop3ImapIn;
        @XmlElement(name = "pop3_imap_out")
        protected long pop3ImapOut;

        /**
         * Gets the value of the domId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDomId() {
            return domId;
        }

        /**
         * Sets the value of the domId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDomId(BigInteger value) {
            this.domId = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the smtpIn property.
         * 
         */
        public long getSmtpIn() {
            return smtpIn;
        }

        /**
         * Sets the value of the smtpIn property.
         * 
         */
        public void setSmtpIn(long value) {
            this.smtpIn = value;
        }

        /**
         * Gets the value of the smtpOut property.
         * 
         */
        public long getSmtpOut() {
            return smtpOut;
        }

        /**
         * Sets the value of the smtpOut property.
         * 
         */
        public void setSmtpOut(long value) {
            this.smtpOut = value;
        }

        /**
         * Gets the value of the pop3ImapIn property.
         * 
         */
        public long getPop3ImapIn() {
            return pop3ImapIn;
        }

        /**
         * Sets the value of the pop3ImapIn property.
         * 
         */
        public void setPop3ImapIn(long value) {
            this.pop3ImapIn = value;
        }

        /**
         * Gets the value of the pop3ImapOut property.
         * 
         */
        public long getPop3ImapOut() {
            return pop3ImapOut;
        }

        /**
         * Sets the value of the pop3ImapOut property.
         * 
         */
        public void setPop3ImapOut(long value) {
            this.pop3ImapOut = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *         <choice>
     *           <element name="plan-guid" type="{}string"/>
     *           <element name="plan-external-id" type="{}string"/>
     *           <element name="no-plan" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         </choice>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter",
        "planGuid",
        "planExternalId",
        "noPlan"
    })
    public static class SwitchSubscription {

        @XmlElement(required = true)
        protected DomainFilterType filter;
        @XmlElement(name = "plan-guid")
        protected String planGuid;
        @XmlElement(name = "plan-external-id")
        protected String planExternalId;
        @XmlElement(name = "no-plan")
        protected Object noPlan;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

        /**
         * Gets the value of the planGuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanGuid() {
            return planGuid;
        }

        /**
         * Sets the value of the planGuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanGuid(String value) {
            this.planGuid = value;
        }

        /**
         * Gets the value of the planExternalId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanExternalId() {
            return planExternalId;
        }

        /**
         * Sets the value of the planExternalId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanExternalId(String value) {
            this.planExternalId = value;
        }

        /**
         * Gets the value of the noPlan property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getNoPlan() {
            return noPlan;
        }

        /**
         * Sets the value of the noPlan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setNoPlan(Object value) {
            this.noPlan = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="filter" type="{}domainFilterType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class SyncSubscription {

        @XmlElement(required = true)
        protected DomainFilterType filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link DomainFilterType }
         *     
         */
        public DomainFilterType getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainFilterType }
         *     
         */
        public void setFilter(DomainFilterType value) {
            this.filter = value;
        }

    }

}
