//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Objects statistics
 * 
 * <p>Java class for objectsStatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="objectsStatType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="clients" type="{}unsignedInt"/>
 *         <element name="domains" type="{}unsignedInt"/>
 *         <element name="active_domains" type="{}unsignedInt"/>
 *         <element name="mail_boxes" type="{}unsignedInt"/>
 *         <element name="mail_redirects" type="{}unsignedInt"/>
 *         <element name="mail_groups" type="{}unsignedInt"/>
 *         <element name="mail_responders" type="{}unsignedInt"/>
 *         <element name="web_users" type="{}unsignedInt"/>
 *         <element name="databases" type="{}unsignedInt"/>
 *         <element name="database_users" type="{}unsignedInt"/>
 *         <element name="problem_clients" type="{}unsignedInt"/>
 *         <element name="problem_domains" type="{}unsignedInt"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectsStatType", propOrder = {
    "clients",
    "domains",
    "activeDomains",
    "mailBoxes",
    "mailRedirects",
    "mailGroups",
    "mailResponders",
    "webUsers",
    "databases",
    "databaseUsers",
    "problemClients",
    "problemDomains"
})
public class ObjectsStatType {

    @XmlElement(defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long clients;
    @XmlElement(defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long domains;
    @XmlElement(name = "active_domains", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long activeDomains;
    @XmlElement(name = "mail_boxes", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long mailBoxes;
    @XmlElement(name = "mail_redirects", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long mailRedirects;
    @XmlElement(name = "mail_groups", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long mailGroups;
    @XmlElement(name = "mail_responders", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long mailResponders;
    @XmlElement(name = "web_users", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long webUsers;
    @XmlElement(defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long databases;
    @XmlElement(name = "database_users", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long databaseUsers;
    @XmlElement(name = "problem_clients", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long problemClients;
    @XmlElement(name = "problem_domains", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected long problemDomains;

    /**
     * Gets the value of the clients property.
     * 
     */
    public long getClients() {
        return clients;
    }

    /**
     * Sets the value of the clients property.
     * 
     */
    public void setClients(long value) {
        this.clients = value;
    }

    /**
     * Gets the value of the domains property.
     * 
     */
    public long getDomains() {
        return domains;
    }

    /**
     * Sets the value of the domains property.
     * 
     */
    public void setDomains(long value) {
        this.domains = value;
    }

    /**
     * Gets the value of the activeDomains property.
     * 
     */
    public long getActiveDomains() {
        return activeDomains;
    }

    /**
     * Sets the value of the activeDomains property.
     * 
     */
    public void setActiveDomains(long value) {
        this.activeDomains = value;
    }

    /**
     * Gets the value of the mailBoxes property.
     * 
     */
    public long getMailBoxes() {
        return mailBoxes;
    }

    /**
     * Sets the value of the mailBoxes property.
     * 
     */
    public void setMailBoxes(long value) {
        this.mailBoxes = value;
    }

    /**
     * Gets the value of the mailRedirects property.
     * 
     */
    public long getMailRedirects() {
        return mailRedirects;
    }

    /**
     * Sets the value of the mailRedirects property.
     * 
     */
    public void setMailRedirects(long value) {
        this.mailRedirects = value;
    }

    /**
     * Gets the value of the mailGroups property.
     * 
     */
    public long getMailGroups() {
        return mailGroups;
    }

    /**
     * Sets the value of the mailGroups property.
     * 
     */
    public void setMailGroups(long value) {
        this.mailGroups = value;
    }

    /**
     * Gets the value of the mailResponders property.
     * 
     */
    public long getMailResponders() {
        return mailResponders;
    }

    /**
     * Sets the value of the mailResponders property.
     * 
     */
    public void setMailResponders(long value) {
        this.mailResponders = value;
    }

    /**
     * Gets the value of the webUsers property.
     * 
     */
    public long getWebUsers() {
        return webUsers;
    }

    /**
     * Sets the value of the webUsers property.
     * 
     */
    public void setWebUsers(long value) {
        this.webUsers = value;
    }

    /**
     * Gets the value of the databases property.
     * 
     */
    public long getDatabases() {
        return databases;
    }

    /**
     * Sets the value of the databases property.
     * 
     */
    public void setDatabases(long value) {
        this.databases = value;
    }

    /**
     * Gets the value of the databaseUsers property.
     * 
     */
    public long getDatabaseUsers() {
        return databaseUsers;
    }

    /**
     * Sets the value of the databaseUsers property.
     * 
     */
    public void setDatabaseUsers(long value) {
        this.databaseUsers = value;
    }

    /**
     * Gets the value of the problemClients property.
     * 
     */
    public long getProblemClients() {
        return problemClients;
    }

    /**
     * Sets the value of the problemClients property.
     * 
     */
    public void setProblemClients(long value) {
        this.problemClients = value;
    }

    /**
     * Gets the value of the problemDomains property.
     * 
     */
    public long getProblemDomains() {
        return problemDomains;
    }

    /**
     * Sets the value of the problemDomains property.
     * 
     */
    public void setProblemDomains(long value) {
        this.problemDomains = value;
    }

}
