//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pleskOS.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="pleskOS">
 *   <restriction base="{}string">
 *     <enumeration value="Windows"/>
 *     <enumeration value="RedHat"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "pleskOS")
@XmlEnum
public enum PleskOS {

    @XmlEnumValue("Windows")
    WINDOWS("Windows"),
    @XmlEnumValue("RedHat")
    RED_HAT("RedHat");
    private final String value;

    PleskOS(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PleskOS fromValue(String v) {
        for (PleskOS c: PleskOS.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
