//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProtectedDirOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ProtectedDirOutput">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="add" type="{}ProtectedDirAddOutput"/>
 *         <element name="set" type="{}ProtectedDirSetOutput"/>
 *         <element name="delete" type="{}ProtectedDirDeleteOutput"/>
 *         <element name="add-user" type="{}ProtectedDirAddUserOutput"/>
 *         <element name="set-user" type="{}ProtectedDirSetUserOutput"/>
 *         <element name="delete-user" type="{}ProtectedDirDeleteUserOutput"/>
 *         <element name="get" type="{}ProtectedDirGetOutput"/>
 *         <element name="get-user" type="{}ProtectedDirGetUserOutput"/>
 *         <element name="get-pd-location-descriptor">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" maxOccurs="unbounded" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <extension base="{}resultFilterType">
 *                           <sequence minOccurs="0">
 *                             <element name="descriptor" type="{}ObjectDescriptor" minOccurs="0"/>
 *                           </sequence>
 *                         </extension>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProtectedDirOutput", propOrder = {
    "addOrSetOrDelete"
})
public class ProtectedDirOutput {

    @XmlElements({
        @XmlElement(name = "add", type = ProtectedDirAddOutput.class),
        @XmlElement(name = "set", type = ProtectedDirSetOutput.class),
        @XmlElement(name = "delete", type = ProtectedDirDeleteOutput.class),
        @XmlElement(name = "add-user", type = ProtectedDirAddUserOutput.class),
        @XmlElement(name = "set-user", type = ProtectedDirSetUserOutput.class),
        @XmlElement(name = "delete-user", type = ProtectedDirDeleteUserOutput.class),
        @XmlElement(name = "get", type = ProtectedDirGetOutput.class),
        @XmlElement(name = "get-user", type = ProtectedDirGetUserOutput.class),
        @XmlElement(name = "get-pd-location-descriptor", type = ProtectedDirOutput.GetPdLocationDescriptor.class)
    })
    protected List<Object> addOrSetOrDelete;

    /**
     * Gets the value of the addOrSetOrDelete property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the addOrSetOrDelete property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddOrSetOrDelete().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProtectedDirAddOutput }
     * {@link ProtectedDirAddUserOutput }
     * {@link ProtectedDirDeleteOutput }
     * {@link ProtectedDirDeleteUserOutput }
     * {@link ProtectedDirGetOutput }
     * {@link ProtectedDirGetUserOutput }
     * {@link ProtectedDirOutput.GetPdLocationDescriptor }
     * {@link ProtectedDirSetOutput }
     * {@link ProtectedDirSetUserOutput }
     * 
     * 
     * @return
     *     The value of the addOrSetOrDelete property.
     */
    public List<Object> getAddOrSetOrDelete() {
        if (addOrSetOrDelete == null) {
            addOrSetOrDelete = new ArrayList<>();
        }
        return this.addOrSetOrDelete;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" maxOccurs="unbounded" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <extension base="{}resultFilterType">
     *                 <sequence minOccurs="0">
     *                   <element name="descriptor" type="{}ObjectDescriptor" minOccurs="0"/>
     *                 </sequence>
     *               </extension>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class GetPdLocationDescriptor {

        protected List<ProtectedDirOutput.GetPdLocationDescriptor.Result> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProtectedDirOutput.GetPdLocationDescriptor.Result }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ProtectedDirOutput.GetPdLocationDescriptor.Result> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <extension base="{}resultFilterType">
         *       <sequence minOccurs="0">
         *         <element name="descriptor" type="{}ObjectDescriptor" minOccurs="0"/>
         *       </sequence>
         *     </extension>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "descriptor"
        })
        public static class Result
            extends ResultFilterType
        {

            protected ObjectDescriptor descriptor;

            /**
             * Gets the value of the descriptor property.
             * 
             * @return
             *     possible object is
             *     {@link ObjectDescriptor }
             *     
             */
            public ObjectDescriptor getDescriptor() {
                return descriptor;
            }

            /**
             * Sets the value of the descriptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ObjectDescriptor }
             *     
             */
            public void setDescriptor(ObjectDescriptor value) {
                this.descriptor = value;
            }

        }

    }

}
