//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResellerOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ResellerOutput">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="add" type="{}ResellerAddOutput"/>
 *         <element name="set">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="get" type="{}ResellerGetOutput"/>
 *         <element name="del">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="ippool-add-ip" type="{}ResellerIpPoolOperationOutput"/>
 *         <element name="ippool-del-ip" type="{}ResellerIpPoolOperationOutput"/>
 *         <element name="ippool-set-ip" type="{}ResellerIpPoolOperationOutput"/>
 *         <element name="cform-buttons-list" type="{}ResellerCFormButtonsListOutput"/>
 *         <element name="get-limit-descriptor" type="{}ResellerDescriptorOutput"/>
 *         <element name="get-permission-descriptor" type="{}ResellerDescriptorOutput"/>
 *         <element name="switch-subscription">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <extension base="{}resultFilterType">
 *                           <sequence minOccurs="0">
 *                             <element name="problems" type="{}string" minOccurs="0"/>
 *                           </sequence>
 *                         </extension>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="convert-to-customer">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="sync-subscription">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <extension base="{}resultFilterType">
 *                           <sequence minOccurs="0">
 *                             <element name="problems" type="{}string" minOccurs="0"/>
 *                           </sequence>
 *                         </extension>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="add-package">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="remove-package">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="enable-aps-filter">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="disable-aps-filter">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="get-domain-list" type="{}resultDomainListOutputType" maxOccurs="unbounded"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResellerOutput", propOrder = {
    "addOrSetOrGet"
})
public class ResellerOutput {

    @XmlElementRefs({
        @XmlElementRef(name = "add", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "set", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "del", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ippool-add-ip", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ippool-del-ip", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ippool-set-ip", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cform-buttons-list", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-limit-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-permission-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "switch-subscription", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "convert-to-customer", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sync-subscription", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "add-package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remove-package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "enable-aps-filter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "disable-aps-filter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-domain-list", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> addOrSetOrGet;

    /**
     * Gets the value of the addOrSetOrGet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the addOrSetOrGet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddOrSetOrGet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ResellerAddOutput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerCFormButtonsListOutput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerDescriptorOutput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerDescriptorOutput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerGetOutput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerIpPoolOperationOutput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerIpPoolOperationOutput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerIpPoolOperationOutput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerOutput.AddPackage }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerOutput.ConvertToCustomer }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerOutput.Del }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerOutput.DisableApsFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerOutput.EnableApsFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerOutput.RemovePackage }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerOutput.Set }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerOutput.SwitchSubscription }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerOutput.SyncSubscription }{@code >}
     * {@link JAXBElement }{@code <}{@link ResultDomainListOutputType }{@code >}
     * 
     * 
     * @return
     *     The value of the addOrSetOrGet property.
     */
    public List<JAXBElement<?>> getAddOrSetOrGet() {
        if (addOrSetOrGet == null) {
            addOrSetOrGet = new ArrayList<>();
        }
        return this.addOrSetOrGet;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class AddPackage {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class ConvertToCustomer {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class Del {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class DisableApsFilter {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class EnableApsFilter {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class RemovePackage {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class Set {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <extension base="{}resultFilterType">
     *                 <sequence minOccurs="0">
     *                   <element name="problems" type="{}string" minOccurs="0"/>
     *                 </sequence>
     *               </extension>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class SwitchSubscription {

        @XmlElement(required = true)
        protected List<ResellerOutput.SwitchSubscription.Result> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResellerOutput.SwitchSubscription.Result }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResellerOutput.SwitchSubscription.Result> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <extension base="{}resultFilterType">
         *       <sequence minOccurs="0">
         *         <element name="problems" type="{}string" minOccurs="0"/>
         *       </sequence>
         *     </extension>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "problems"
        })
        public static class Result
            extends ResultFilterType
        {

            protected String problems;

            /**
             * Gets the value of the problems property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProblems() {
                return problems;
            }

            /**
             * Sets the value of the problems property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProblems(String value) {
                this.problems = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <extension base="{}resultFilterType">
     *                 <sequence minOccurs="0">
     *                   <element name="problems" type="{}string" minOccurs="0"/>
     *                 </sequence>
     *               </extension>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class SyncSubscription {

        @XmlElement(required = true)
        protected List<ResellerOutput.SyncSubscription.Result> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResellerOutput.SyncSubscription.Result }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResellerOutput.SyncSubscription.Result> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <extension base="{}resultFilterType">
         *       <sequence minOccurs="0">
         *         <element name="problems" type="{}string" minOccurs="0"/>
         *       </sequence>
         *     </extension>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "problems"
        })
        public static class Result
            extends ResultFilterType
        {

            protected String problems;

            /**
             * Gets the value of the problems property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProblems() {
                return problems;
            }

            /**
             * Sets the value of the problems property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProblems(String value) {
                this.problems = value;
            }

        }

    }

}
