//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResellerTemplateOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ResellerTemplateOutputType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="add" type="{}ResellerTemplateOutputAddType"/>
 *         <element name="get" type="{}ResellerTemplateOutputGetType"/>
 *         <element name="del" type="{}ResellerTemplateOutputDelType"/>
 *         <element name="set" type="{}ResellerTemplateOutputSetType"/>
 *         <element name="add-package">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="remove-package">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="get-limit-descriptor" type="{}ResellerDescriptorOutput"/>
 *         <element name="get-permission-descriptor" type="{}ResellerDescriptorOutput"/>
 *         <element name="enable-aps-filter">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="disable-aps-filter">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="duplicate" type="{}ResellerTemplateOutputAddType"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResellerTemplateOutputType", propOrder = {
    "addOrGetOrDel"
})
public class ResellerTemplateOutputType {

    @XmlElementRefs({
        @XmlElementRef(name = "add", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "del", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "set", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "add-package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remove-package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-limit-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "get-permission-descriptor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "enable-aps-filter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "disable-aps-filter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "duplicate", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> addOrGetOrDel;

    /**
     * Gets the value of the addOrGetOrDel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the addOrGetOrDel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddOrGetOrDel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ResellerDescriptorOutput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerDescriptorOutput }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerTemplateOutputAddType }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerTemplateOutputAddType }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerTemplateOutputDelType }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerTemplateOutputGetType }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerTemplateOutputSetType }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerTemplateOutputType.AddPackage }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerTemplateOutputType.DisableApsFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerTemplateOutputType.EnableApsFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link ResellerTemplateOutputType.RemovePackage }{@code >}
     * 
     * 
     * @return
     *     The value of the addOrGetOrDel property.
     */
    public List<JAXBElement<?>> getAddOrGetOrDel() {
        if (addOrGetOrDel == null) {
            addOrGetOrDel = new ArrayList<>();
        }
        return this.addOrGetOrDel;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class AddPackage {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class DisableApsFilter {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class EnableApsFilter {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="result" type="{}resultFilterType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class RemovePackage {

        @XmlElement(required = true)
        protected List<ResultFilterType> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultFilterType }
         * 
         * 
         * @return
         *     The value of the result property.
         */
        public List<ResultFilterType> getResult() {
            if (result == null) {
                result = new ArrayList<>();
            }
            return this.result;
        }

    }

}
