//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Server general info
 * 
 * <p>Java class for serverGenInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="serverGenInfoType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="server_name" type="{}string"/>
 *         <element name="server_guid" type="{}string"/>
 *         <element name="external-id" type="{}string" minOccurs="0"/>
 *         <element name="vps-optimized-status" type="{}VPSOptimizedStatus" minOccurs="0"/>
 *         <element name="mode" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{}string">
 *               <enumeration value="poweruser"/>
 *               <enumeration value="standard"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serverGenInfoType", propOrder = {
    "serverName",
    "serverGuid",
    "externalId",
    "vpsOptimizedStatus",
    "mode"
})
public class ServerGenInfoType {

    @XmlElement(name = "server_name", required = true)
    protected String serverName;
    @XmlElement(name = "server_guid", required = true)
    protected String serverGuid;
    @XmlElement(name = "external-id")
    protected String externalId;
    @XmlElement(name = "vps-optimized-status")
    protected VPSOptimizedStatus vpsOptimizedStatus;
    protected String mode;

    /**
     * Gets the value of the serverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * Sets the value of the serverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerName(String value) {
        this.serverName = value;
    }

    /**
     * Gets the value of the serverGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerGuid() {
        return serverGuid;
    }

    /**
     * Sets the value of the serverGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerGuid(String value) {
        this.serverGuid = value;
    }

    /**
     * Gets the value of the externalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalId(String value) {
        this.externalId = value;
    }

    /**
     * Gets the value of the vpsOptimizedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link VPSOptimizedStatus }
     *     
     */
    public VPSOptimizedStatus getVpsOptimizedStatus() {
        return vpsOptimizedStatus;
    }

    /**
     * Sets the value of the vpsOptimizedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link VPSOptimizedStatus }
     *     
     */
    public void setVpsOptimizedStatus(VPSOptimizedStatus value) {
        this.vpsOptimizedStatus = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

}
