//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Domain general setup info
 * 
 * <p>Java class for setGenSetupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="setGenSetupType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="11" minOccurs="0">
 *         <element name="status" type="{}objectStatus" minOccurs="0"/>
 *         <element name="name" type="{}domainName" minOccurs="0"/>
 *         <choice minOccurs="0">
 *           <element name="owner-id" type="{}id_type" minOccurs="0"/>
 *           <element name="owner-login" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           <element name="owner-guid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           <element name="owner-external-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         </choice>
 *         <element name="ip_address" type="{}ip_address" minOccurs="0"/>
 *         <element name="guid" type="{}NoneType" minOccurs="0"/>
 *         <element name="external-id" type="{}string" minOccurs="0"/>
 *         <element name="admin-as-vendor" type="{}NoneType" minOccurs="0"/>
 *         <element name="description" type="{}string" minOccurs="0"/>
 *         <element name="admin-description" type="{}string" minOccurs="0"/>
 *         <element name="reseller-description" type="{}string" minOccurs="0"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setGenSetupType", propOrder = {
    "statusOrNameOrOwnerId"
})
public class SetGenSetupType {

    @XmlElementRefs({
        @XmlElementRef(name = "status", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "owner-id", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "owner-login", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "owner-guid", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "owner-external-id", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ip_address", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "guid", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "external-id", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "admin-as-vendor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "admin-description", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "reseller-description", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> statusOrNameOrOwnerId;

    /**
     * Gets the value of the statusOrNameOrOwnerId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the statusOrNameOrOwnerId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatusOrNameOrOwnerId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link NoneType }{@code >}
     * {@link JAXBElement }{@code <}{@link NoneType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * 
     * @return
     *     The value of the statusOrNameOrOwnerId property.
     */
    public List<JAXBElement<?>> getStatusOrNameOrOwnerId() {
        if (statusOrNameOrOwnerId == null) {
            statusOrNameOrOwnerId = new ArrayList<>();
        }
        return this.statusOrNameOrOwnerId;
    }

}
