//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Domain general setup info
 * 
 * <p>Java class for setSiteGenSetupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="setSiteGenSetupType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <all>
 *         <element name="status" type="{}objectStatus" minOccurs="0"/>
 *         <element name="name" type="{}domainName" minOccurs="0"/>
 *         <element name="guid" type="{}NoneType" minOccurs="0"/>
 *         <element name="description" type="{}string" minOccurs="0"/>
 *         <element name="turn-off-action" type="{}turnOffAction" minOccurs="0"/>
 *       </all>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setSiteGenSetupType", propOrder = {

})
public class SetSiteGenSetupType {

    protected BigInteger status;
    protected String name;
    protected NoneType guid;
    protected String description;
    @XmlElement(name = "turn-off-action")
    @XmlSchemaType(name = "string")
    protected TurnOffAction turnOffAction;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatus(BigInteger value) {
        this.status = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link NoneType }
     *     
     */
    public NoneType getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoneType }
     *     
     */
    public void setGuid(NoneType value) {
        this.guid = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the turnOffAction property.
     * 
     * @return
     *     possible object is
     *     {@link TurnOffAction }
     *     
     */
    public TurnOffAction getTurnOffAction() {
        return turnOffAction;
    }

    /**
     * Sets the value of the turnOffAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TurnOffAction }
     *     
     */
    public void setTurnOffAction(TurnOffAction value) {
        this.turnOffAction = value;
    }

}
