//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package plesk.xml.api;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebspaceMailPreferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="WebspaceMailPreferences">
 *   <complexContent>
 *     <extension base="{}MailPreferences">
 *       <sequence>
 *         <element name="outgoing-messages-mbox-limit" type="{}string" minOccurs="0"/>
 *         <element name="outgoing-messages-domain-limit" type="{}string" minOccurs="0"/>
 *         <element name="outgoing-messages-subscription-limit" type="{}string" minOccurs="0"/>
 *         <element name="outgoing-messages-enable-sendmail" type="{}booleanWithDefault" minOccurs="0"/>
 *         <element name="outgoing-messages-overlimit-percent" type="{}int" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebspaceMailPreferences", propOrder = {
    "outgoingMessagesMboxLimit",
    "outgoingMessagesDomainLimit",
    "outgoingMessagesSubscriptionLimit",
    "outgoingMessagesEnableSendmail",
    "outgoingMessagesOverlimitPercent"
})
public class WebspaceMailPreferences
    extends MailPreferences
{

    @XmlElement(name = "outgoing-messages-mbox-limit")
    protected String outgoingMessagesMboxLimit;
    @XmlElement(name = "outgoing-messages-domain-limit")
    protected String outgoingMessagesDomainLimit;
    @XmlElement(name = "outgoing-messages-subscription-limit")
    protected String outgoingMessagesSubscriptionLimit;
    @XmlElement(name = "outgoing-messages-enable-sendmail")
    @XmlSchemaType(name = "string")
    protected BooleanWithDefault outgoingMessagesEnableSendmail;
    @XmlElement(name = "outgoing-messages-overlimit-percent")
    protected BigInteger outgoingMessagesOverlimitPercent;

    /**
     * Gets the value of the outgoingMessagesMboxLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutgoingMessagesMboxLimit() {
        return outgoingMessagesMboxLimit;
    }

    /**
     * Sets the value of the outgoingMessagesMboxLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutgoingMessagesMboxLimit(String value) {
        this.outgoingMessagesMboxLimit = value;
    }

    /**
     * Gets the value of the outgoingMessagesDomainLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutgoingMessagesDomainLimit() {
        return outgoingMessagesDomainLimit;
    }

    /**
     * Sets the value of the outgoingMessagesDomainLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutgoingMessagesDomainLimit(String value) {
        this.outgoingMessagesDomainLimit = value;
    }

    /**
     * Gets the value of the outgoingMessagesSubscriptionLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutgoingMessagesSubscriptionLimit() {
        return outgoingMessagesSubscriptionLimit;
    }

    /**
     * Sets the value of the outgoingMessagesSubscriptionLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutgoingMessagesSubscriptionLimit(String value) {
        this.outgoingMessagesSubscriptionLimit = value;
    }

    /**
     * Gets the value of the outgoingMessagesEnableSendmail property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanWithDefault }
     *     
     */
    public BooleanWithDefault getOutgoingMessagesEnableSendmail() {
        return outgoingMessagesEnableSendmail;
    }

    /**
     * Sets the value of the outgoingMessagesEnableSendmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanWithDefault }
     *     
     */
    public void setOutgoingMessagesEnableSendmail(BooleanWithDefault value) {
        this.outgoingMessagesEnableSendmail = value;
    }

    /**
     * Gets the value of the outgoingMessagesOverlimitPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutgoingMessagesOverlimitPercent() {
        return outgoingMessagesOverlimitPercent;
    }

    /**
     * Sets the value of the outgoingMessagesOverlimitPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutgoingMessagesOverlimitPercent(BigInteger value) {
        this.outgoingMessagesOverlimitPercent = value;
    }

}
